var _collectModsDatas = [{
	"code" : "modco_contmpb",
	"nom" : "Conteneur plastique",
	"nom_en" : "Plastic container",
	"libelleBouton" : "Conteneur plastique",
	"libelleBouton_en" : "Plastic container",
	"modesCollecte" : "false",
	"descr" : "On peut mettre tous les bouteilles transparentes (eau, soda), les bouteilles de lait, bouteille d'huile (en plastique), les flacons (lessive, javel, nettoyant ménager...) sauf ceux ayant contenus des produits toxiques (ayant une croix rouge) ou inflammables (flamme rouge).<br/>On ne doit pas mettre les barquettes en polystyrène, les pots de yaourts, les sacs plastiques de supermarché.<BR/>Voir <I><A HREF='fich:fiche_contembjournmag'>fiche 'Conteneur emballages journaux magazines'</A></I>",
	"descr_en" : "You can put all transparent bottles (water, soda), milk bottles, bottle of oil (plastic) bottles (detergent, bleach, household cleaners ...) except those that contained toxic products (with . Red Cross) or flammable (flame red) <br/> should not put them in polystyrene trays, yoghurt pots, plastic bags of supermarket <BR/> See <I> <A HREF = 'File.: fiche_contembjournmag '> file' container packaging magazines newspapers' </A> </ I>",
	"admis" : "bouteilles transparentes (eau, soda), les bouteilles de lait, bouteille d'huile (en plastique), les flacons (lessive, javel, nettoyant ménager...) sauf ceux ayant contenus des produits toxiques ",
	"admis_en" : "transparent bottles (water, soda), milk bottles, bottle of oil (plastic) bottles (detergent, bleach, household cleaners ...) except those that contained toxic products",
	"icone" : "modco",
	"image" : "conteneur_plastique_mini.png",
	"mots_cles" : "conteneur,plastique",
	"mots_cles_en" : "container,plastic"
}, {
	"code" : "modco_contpapiercarton",
	"nom" : "Conteneur papier carton",
	"nom_en" : "Paperboard container",
	"libelleBouton" : "Conteneur<br/>papier carton",
	"libelleBouton_en" : "Paperboard container",
	"modesCollecte" : "false",
	"descr" : "On peut mettre : cartons (bruns), cartonnettes, emballage en carton, enveloppe, feuilles, journaux, magazines, prospectus,  boîte à œuf en carton.",
	"descr_en" : "You can put: cartons (brown), cardboards, carton, envelope, paper, newspapers, magazines, brochures, egg carton.",
	"admis" : "cartons (bruns), cartonnettes, emballage en carton, enveloppe, feuilles, journaux, magazines, prospectus,  boîte à œuf en carton",
	"admis_en" : "cartons (brown), cardboards, carton, envelope, paper, newspapers, magazines, brochures, egg carton",
	"cons" : "cons_souille",
	"icone" : "modco",
	"image" : "conteneur_carton_mini.png",
	"mots_cles" : "conteneur,papier,carton",
	"mots_cles_en" : "container,paper,cardboard"
}, {
	"code" : "modco_contverre",
	"nom" : "Conteneur verre",
	"nom_en" : "Glass container",
	"libelleBouton" : "Conteneur verre",
	"libelleBouton_en" : "Glass container",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/conteneur_verre_instructions_2.jpg' WIDTH='200px' /> <IMG SRC='resources/images/conteneur_verre_instructions.jpg' WIDTH='200px' /><BR/>On peut mettre le verre <b>ménager</b> : bouteilles, pots, bocaux.<br/><br/>En revanche il ne faut pas mettre la vaisselle, les pôts, les ampoules.",
	"descr_en" : "<IMG SRC='resources/images/conteneur_verre_instructions_2.jpg 'WIDTH='200px' /> <IMG SRC='resources/images/conteneur_verre_instructions.jpg' WIDTH='200px' /> <BR/> can put the glass <b>Home </b>: bottles, pots, jars <br/> But we must not put the dishes, pots, ampoules..",
	"admis" : "bouteilles, pots, bocaux",
	"admis_en" : "bottles, pots, jars",
	"cons" : "cons_verre,cons_sans_bouchon_ni_couvercle,cons_nbconteneurverre",
	"icone" : "modco",
	"image" : "conteneur_verre_mini.png",
	"mots_cles" : "conteneur,verre",
	"mots_cles_en" : "container,glass"
}, {
	"code" : "modco_contembjournmag",
	"nom" : "Conteneur emballages journaux magazines",
	"nom_en" : "Container packaging newspapers magazines",
	"libelleBouton" : "Conteneur<br/>emballages<br/>journaux magazines",
	"libelleBouton_en" : "Container packaging newspapers magazines",
	"modesCollecte" : "false",
	"descr" : "On peut mettre : boîte de conserve, barquette aluminium, cannette, aérosol, bouteille métal sirop, bouteilles d'eau, flacon, brique (jus de fruit, lait), cartonnettes, papier, journaux, magazines.<BR/>Voir <A HREF='fich:fiche_contembjournmag'>fiche 'Conteneur emballages journaux magazines'</A></I>",
	"descr_en" : "You can put. Tin, aluminum trays, cans, aerosols, metal bottle syrup, water bottles, bottle, brick (fruit, milk juice), cardboards, paper, newspapers, magazines <BR/> See <A HREF = 'File: fiche_contembjournmag'> file 'container packaging magazines newspapers' </A> </ I>",
	"admis" : "boîte de conserve, barquette aluminium, cannette, aérosol, bouteille métal sirop, bouteilles d'eau, flacon, brique (jus de fruit, lait), cartonnettes, papier, journaux, magazines",
	"admis_en" : "tin, aluminum trays, cans, aerosol metal syrup bottle, water bottles, bottle, brick (fruit, milk juice), cardboards, paper, newspapers, magazines",
	"cons" : "cons_sans_bouchon_ni_couvercle",
	"icone" : "modco",
	"image" : "conteneur_emballages_journaux_magazines_mini.png",
	"mots_cles" : "conteneur,emballages,journaux,magazines",
	"mots_cles_en" : "container,packaging,newspapers,magazines"
}, {
	"code" : "modco_bacbleuhorsnantes",
	"nom" : "Bacs bleus (hors Nantes)",
	"nom_en" : "Blue bins (excluding Nantes)",
	"libelleBouton" : "Bacs bleus (hors Nantes)",
	"libelleBouton_en" : "Blue bins (excluding Nantes)",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/bac_bleu_mini.png' ALIGN='right' WIDTH='150px' />On met les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "<IMG SRC='resources/images/bac_bleu_mini.png' align='right' WIDTH='150px' /> It puts the <B> non-recycled household waste </b>.",
	"cons" : "cons_bac_casse,cons_collectes_bacs,cons_arcencielvalorena",
	"icone" : "modco",
	"image" : "bac_bleu_mini.png",
	"mots_cles" : "bacs,bleus",
	"mots_cles_en" : "bins,blue"
}, {
	"code" : "modco_bacbleu",
	"nom" : "Bacs bleus",
	"nom_en" : "Blue bins",
	"libelleBouton" : "Bacs bleus",
	"libelleBouton_en" : "Blue bins",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/bac_bleu_mini.png' ALIGN='right' WIDTH='150px' />On met les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "<IMG SRC='resources/images/bac_bleu_mini.png' align='right' WIDTH='150px' /> It puts the <B> non-recycled household waste </b>.",
	"cons" : "cons_bac_casse,cons_collectes_bacs,cons_arcencielvalorena",
	"icone" : "modco",
	"image" : "bac_bleu_mini.png",
	"mots_cles" : "bacs,bleus",
	"mots_cles_en" : "bins,blue"
}, {
	"code" : "modco_bacjaunenantes",
	"nom" : "Bacs jaunes (Nantes)",
	"nom_en" : "Yellow Bacs (Nantes)",
	"libelleBouton" : "Bacs jaunes (Nantes)",
	"libelleBouton_en" : "Yellow Bacs (Nantes)",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/bac_jaune_en_cours_mini.png' ALIGN='right' WIDTH='150px' /><BR/>On peut mettre : cartons, cartonnettes, enveloppes, feuilles, journaux, magazines, briques, <B>tous les types de plastique</B> (bouteilles eau soda huile, bouchons, flacons, pots de yaourt, pots de crème fraîche, barquettes, films plastique)</B>,  barquettes aluminium, canettes, boîtes de conserves, bombes aérosols.<BR/>Voir <I><A HREF='fich:fiche_bacjaune'>fiche 'Bacs jaunes et bleus'</A></I> .",
	"descr_en" : "<IMG SRC='resources/images/bac_jaune_en_cours_mini.png' align='right' WIDTH='150px' /> You can put <BR/>: cartons, cardboards, envelopes, sheets, newspapers, magazines, bricks, <B> all types of plastics </b> (soda water bottles oil, corks, bottles, yogurt cups, cream jars, trays, plastic films) </b>, aluminum trays, cans, tins, aerosols. <BR/> See <I> <A HREF='fich:fiche_bacjaune'> sheet 'yellow bins and blue' </A> </ I>.",
	"cons" : "cons_pasuniquementbouteilleflacon,cons_bac_casse,cons_collectes_bacs",
	"icone" : "modco",
	"image" : "bac_jaune_en_cours_mini.png",
	"mots_cles" : "bacs,jaunes",
	"mots_cles_en" : "bins,yellow"
}, {
	"code" : "modco_bacjaune",
	"nom" : "Bacs jaunes",
	"nom_en" : "Yellow Bacs",
	"libelleBouton" : "Bacs jaunes",
	"libelleBouton_en" : "Yellow Bacs",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/bac_jaune_en_cours_mini.png' ALIGN='right' WIDTH='150px' /><BR/>On peut mettre : cartons, cartonnettes, enveloppes, feuilles, journaux, magazines, briques, les bouteilles eau soda huile, bouchons, flacons,  barquettes aluminium, canettes, boîtes de conserves, bombes aérosols.<BR/>Voir <I><A HREF='fich:fiche_bacjaune'>fiche 'Bacs jaunes et bleus'</A></I>.",
	"descr_en" : "<IMG SRC='resources/images/bac_jaune_en_cours_mini.png' align='right' WIDTH='150px' /> You can put <BR/>: cartons, cardboards, envelopes, sheets, newspapers, magazines, bricks, water bottles soda oil, corks, bottles, aluminum trays, cans, tins, aerosols. <BR/> bombs See <I> <A HREF='fich:fiche_bacjaune'> sheet 'blue and yellow Bacs' </A> </ I>.",
	"cons" : "cons_pasuniquementbouteilleflacon,cons_bac_casse,cons_collectes_bacs",
	"icone" : "modco",
	"image" : "bac_jaune_en_cours_mini.png",
	"mots_cles" : "bacs,jaunes",
	"mots_cles_en" : "bins,yellow"
}, {
	"code" : "modco_sacbleu",
	"nom" : "Sacs bleus",
	"nom_en" : "Blue bags",
	"libelleBouton" : "Sacs bleus",
	"libelleBouton_en" : "Blue bags",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/nantes/sac_bleu_mini.png' ALIGN='right' WIDTH='150px' />On met dans les sacs bleus les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "<IMG SRC='resources/images/nantes/sac_bleu_mini.png' align='right' WIDTH='150px' /> are placed in blue bags the <B> non-recycled household waste </b>.",
	"cons" : "cons_noeudtrisac,cons_passacpoubelle",
	"icone" : "modco",
	"image" : "Nantes/sac_bleu_mini.png",
	"mots_cles" : "sacs,bleus",
	"mots_cles_en" : "bags,blue"
}, {
	"code" : "modco_sacjaune",
	"nom" : "Sacs jaunes",
	"nom_en" : "Yellow bags",
	"libelleBouton" : "Sacs jaunes",
	"libelleBouton_en" : "Yellow bags",
	"modesCollecte" : "false",
	"descr" : "<IMG SRC='resources/images/nantes/sac_jaune_mini.png' ALIGN='right' WIDTH='150px' /><UL>On peut mettre : cartons, cartonnettes, enveloppes, feuilles, journaux, magazines, prospectus, boîtes à œuf en carton, briques, bouteilles avec bouchons (eau, soda, huile), flacons, barquettes aluminium, canettes, boîtes de conserves, bombes aérosols.<BR/>Voir <I><A HREF='fich:fiche_sacjaune'>fiche 'Sacs jaunes et bleus'</A></I> .",
	"descr_en" : "<IMG SRC='resources/images/nantes/sac_jaune_mini.png' align='right' WIDTH='150px' /> <UL> You can put: cartons, cardboards, envelopes, sheets, newspapers, magazines, brochures, egg boxes cardboard, bricks, bottles with caps (water, soda, oil), bottles, aluminum trays, cans, tins, aerosols. <BR/> See <I> <A HREF='fich:fiche_sacjaune'> sheet 'Bags yellow and blue '</A> </ I>.",
	"cons" : "cons_souille,cons_noeudtrisac,cons_passacpoubelle",
	"icone" : "modco",
	"image" : "nantes/sac_jaune_mini.png",
	"mots_cles" : "sacs,jaunes",
	"mots_cles_en" : "bags,yellow"
}, {
	"code" : "modco_ecopoint",
	"nom" : "Écopoint",
	"nom_en" : "Ecopoint",
	"libelleBouton" : "Écopoint",
	"libelleBouton_en" : "Ecopoint",
	"modesCollecte" : "false",
	"descr" : "Les Ecopoints sont des mini-déchèteries où seuls les gravats ne sont pas admis.<BR/>Les déchets suivants sont admis :encombrants, appareils électriques, déchets toxiques en petites quantités, déchets verts, bouteilles et flacons plastiques, papiers, cartons, cartonnettes, verre ménager (pôts, bouteilles), métal<BR/>Voir <I><A HREF='fich:fiche_ecopoint'>fiche 'Déchèteries / écopoint'</A></I> .",
	"descr_en" : "The Ecopoints are mini-waste collection centers where only rubble are allowed <BR/> The following shall be permitted:. Bulky, electrical appliances, toxic waste in small quantities, green waste, plastic bottles, paper, cardboard, cardboards, glass household (Pots, bottles), metal <BR/> See <I> <A HREF='fich:fiche_ecopoint'> sheet 'déchèteries / Ecopoint' </ A> </ I>.",
	"icone" : "modco",
	"image" : "nantes/ecopoint_viarme_mini.png",
	"mots_cles" : "ecopoint",
	"mots_cles_en" : "ecopoint"
}, {
	"code" : "modco_contomr",
	"nom" : "Conteneurs ordures ménagers",
	"nom_en" : "Container for household waste",
	"libelleBouton" : "Conteneurs ordures ménagers",
	"libelleBouton_en" : "Container for household waste",
	"modesCollecte" : "false",
	"descr" : "On met les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "It puts the <B> non-recycled household waste </b>.",
	"image" : "conteneur_enterre.png",
	"mots_cles" : "conteneur,dechet,menager",
	"mots_cles_en" : "container,waste,household"
}, {
	"code" : "modco_dechetssecs",
	"nom" : "Conteneurs déchets secs",
	"nom_en" : "Containers dry waste",
	"libelleBouton" : "Conteneurs déchets secs",
	"libelleBouton_en" : "Containers dry waste",
	"modesCollecte" : "false",
	"descr" : "On met les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "It puts the <B> non-recycled household waste </b>.",
	"image" : "conteneur_ordure_menageres_petit.png",
	"mots_cles" : "conteneurs,dechets,secs",
	"mots_cles_en" : "containers,waste,dry"
}, {
	"code" : "modco_reemploi",
	"nom" : "Entreprises et assos spécialisées",
	"nom_en" : "Specialized companies and assos",
	"libelleBouton" : "Entreprises et assos spécialisées",
	"libelleBouton_en" : "Specialized companies and assos",
	"sous_modes_collecte" : "smco_reempelectromenag,smco_reempinfo,smco_reempcartouchetoner,smco_reemplivreCD,smco_reempjouet,smco_reempmeuble,smco_reempvet,smco_reempdivers,smco_batiment,smco_vaisselle,smco_papier,smco_plastique,smco_velo",
	"modesCollecte" : "false",
	"descr" : "De très nombreuses associations et entreprises solidaires récupèrent les déchets pour qu'ils aient une deuxième vie. Elles récupèrent : jouets, cartouches d'imprimante, électroménager, anciens appareils informatique, livres, revues, CD, BD, meubles, vêtements...",
	"descr_en" : "Numerous associations and several companies collect waste for them to have a second life. They retrieve toys, printer cartridges, appliances, old computer equipment, books, magazines, CDs, comics, furniture, clothing ...",
	"cons" : "cons_deuxiemevie",
	"icone" : "modco",
	"image" : "structures_reemplois_mini.png",
	"mots_cles" : "entreprise,association,asso",
	"mots_cles_en" : "company,association,asso"
}, {
	"code" : "modco_pointsdevente",
	"nom" : "Reprise en points de vente",
	"nom_en" : "Recovery in retail outlets",
	"libelleBouton" : "Reprise en points de vente",
	"libelleBouton_en" : "Recovery in retail outlets",
	"sous_modes_collecte" : "smco_vendeurcartoucheencre,smco_vendeurpile,smco_reprise,smco_vendeur_lampe_eco,smco_vendeurcassevoiture,smco_garage",
	"modesCollecte" : "false",
	"descr" : "Les points de vente sont obligés de récupérer les objets usagés s'ils les vendent : cartouches d'imprimantes, piles et accumulateurs, ampoules basse consommation, tubes fluorescent (néons).",
	"descr_en" : "The outlets are obliged to recover the used items they sell: printer cartridges, batteries, energy saving light bulbs, fluorescent tubes (neons).",
	"cons" : "cons_recuppdv1,cons_recuppdv2",
	"icone" : "modco",
	"image" : "recyclage_point_de_vente_mini.png",
	"mots_cles" : "reprise,vente",
	"mots_cles_en" : "recovery,sale"
}, {
	"code" : "modco_decheterie",
	"nom" : "Déchèteries",
	"nom_en" : "Déchèteries",
	"libelleBouton" : "Déchèteries",
	"libelleBouton_en" : "Déchèteries",
	"modesCollecte" : "false",
	"descr" : "<UL>Les déchets suivants sont admis : déblais, gravats, encombrants, appareils électriques, déchets toxiques (peinture, vernis, colle, diluants, batteries, huiles moteur), déchets verts, bouteilles et flacons plastiques, papiers, cartons, cartonnettes, verre ménager (pôts, bouteilles), métal.<BR/>Voir <I><A HREF='fich:fiche_ecopoint'>fiche 'Déchèteries / écopoint'</A></I> .",
	"descr_en" : "<UL> The following shall be permitted: rubble, rubble, bulky, electrical appliances, toxic waste (paint, varnish, glue, thinners, batteries, motor oil), green waste, plastic bottles, paper, cardboard, cardboards, glass household (Pots, bottles), metal. <BR/> See <I> <A HREF='fich:fiche_ecopoint'> sheet 'déchèteries / Ecopoint' </A> </ I>.",
	"icone" : "modco",
	"image" : "panneau_dechetterie_mini.png",
	"mots_cles" : "decheteries",
	"mots_cles_en" : "decheteries"
}, {
	"code" : "modco_compostage",
	"nom" : "Compostage",
	"nom_en" : "Composting",
	"libelleBouton" : "Compostage",
	"libelleBouton_en" : "Composting",
	"modesCollecte" : "false",
	"descr" : "thé, épluchure, papier à usage unique (papier toilette, essuie-tout), plante, reste de repas (nourriture)<BR/>Voir <I><A HREF='fich:fiche_compostage'>fiche 'Compostage'</A></I> .",
	"descr_en" : "tea, peel, disposable paper (toilet paper, paper towels), plant, rest of meals (food) <BR/> See <I> <A HREF='fich:fiche_compostage'> sheet 'Composting' </ A > </ I>.",
	"image" : "composteur_mini.png",
	"mots_cles" : "compostage",
	"mots_cles_en" : "composting"
}, {
	"code" : "modco_encombrant",
	"nom" : "Point dépôt encombrant",
	"nom_en" : "Point bulky filing",
	"libelleBouton" : "Point dépôt encombrant",
	"libelleBouton_en" : "Point bulky filing",
	"modesCollecte" : "false",
	"descr" : "Pour les logements verticaux (appartement...) les encombrants sont récupérés à jour fixe dans la semaine (affiché en général en bas de l'immeuble).<br/>Pour les logements pavillonnaires (maisons...) le ramassage se fait sur rendez-vous à prendre par téléphone.<BR/>Voir <I>fiche 'Collecte des encombrants'</I>",
	"descr_en" : "For vertical housing (apartment ...) are recovered bulky fixed day in the week (usually displayed at the bottom of the building). In order to the suburban housing (houses ...) collection is appointment to be taken by phone. <BR/> See <I> sheet 'Collection of bulky </ I>",
	"icone" : "modco",
	"image" : "encombrant_mini.png",
	"mots_cles" : "point,depot,encombrant",
	"mots_cles_en" : "point,deposit,bulky"
}, {
	"code" : "smco_conteneurlerelais",
	"nom" : "Conteneur vêtements",
	"nom_en" : "Container clothing",
	"libelleBouton" : "Conteneur vêtements",
	"libelleBouton_en" : "Container clothing",
	"modesCollecte" : "false",
	"descr" : "Vous pouvez déposer vêtements, linge de maison, chaussures (liées par paire), maroquinerie <B>dans un sac bien fermé</B>.<br/>Attention ces vêtements sont <b>revendus</b> mais ne sont pas redistribués gratuitement, même si des logos sont collés sur le conteneur. Voir <a href='fiche:fiche_contvet'>Conteneurs de vêtements</a>",
	"descr_en" : "You can drop clothes, linen, footwear (linked in pairs), leather goods <B> in a sealed bag </b>. Caution <br/> these clothes are <b> sold </b> but are not redistributed for free, even if logos are pasted on the container. See <a href='fiche:fiche_contvet'> clothing containers </a>",
	"cons" : "cons_lerelais",
	"icone" : "modco",
	"image" : "conteneur_lerelais_mini.png",
	"mots_cles" : "conteneur,vetements",
	"mots_cles_en" : "container,clothing"
}, {
	"code" : "smco_reempelectromenag  ",
	"nom" : "Réemploi appareils électroménager",
	"nom_en" : "Reuse household appliances",
	"libelleBouton" : "Réemploi appareils électroménager",
	"libelleBouton_en" : "Reuse household appliances",
	"modesCollecte" : "true",
	"descr" : "Réemploi des appareils électroménager",
	"descr_en" : "Reuse of household appliances",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,appareil,electromenager",
	"mots_cles_en" : "reuse,apparatus,appliances"
}, {
	"code" : "smco_reempinfo",
	"nom" : "Réemploi appareils informatique",
	"nom_en" : "Reuse computer devices",
	"libelleBouton" : "Réemploi appareils informatique",
	"libelleBouton_en" : "Reuse computer devices",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes ('Alis 44' à Nantes, 'Actif Ouest' à Saint-Herblain, 'Nâga' à Rezé) récupèrent les anciens apareils informatiques. <br/>Voir page 'lieux'.",
	"descr_en" : "Several organizations (Alis 44 'in Nantes, western Active' in Saint-Herblain, 'Naga' in Rezé) recover old computer apareils. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,appareil,informatique",
	"mots_cles_en" : "reuse,appliance,computer"
}, {
	"code" : "smco_reempcartouchetoner",
	"nom" : "Réemploi cartouches encres et tuners",
	"nom_en" : "Reuse ink cartridges and tuners",
	"libelleBouton" : "Réemploi cartouches encres et tuners",
	"libelleBouton_en" : "Reuse ink cartridges and tuners",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes ('Lever l'encre' et 'Oce'encre' à Nantes, 'encre Station' à Saint-Herblain) récupèrent les anciennes cartouches d'encrest. <br/>Voir page 'lieux'.",
	"descr_en" : "Several agencies ('Sunrise ink' and 'Oce'encre' in Nantes, Ink Station 'in Saint-Herblain) recover old cartridges encrest. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,cartouche,encre,tuner",
	"mots_cles_en" : "re,use,cartridges,ink,tuner"
}, {
	"code" : "smco_reemplivreCD",
	"nom" : "Réemploi livre/BD/CD/DVD",
	"nom_en" : "Book reuse / BD / CD / DVD",
	"libelleBouton" : "Réemploi livre/BD/CD/DVD",
	"libelleBouton_en" : "Book reuse / BD / CD / DVD",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes (association <a href='lieu:stco_reemploi51'>Nantes écologie</a>, <a href='lieu:stco_reemploi47'>La croix rouge</a>...) récupèrent les anciens livres.",
	"descr_en" : "Several organizations (<a href='lieu:stco_reemploi51'> Nantes </a> ecology association, <a href='lieu:stco_reemploi47'> The red cross </a> ...) recover the ancient books.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,livre/bd/cd/dvd",
	"mots_cles_en" : "reuse,book,bd,cd,dvd"
}, {
	"code" : "smco_reempjouet",
	"nom" : "Réemploi jouets",
	"nom_en" : "Reuse toys",
	"libelleBouton" : "Réemploi jouets",
	"libelleBouton_en" : "Reuse toys",
	"sous_modes_collecte" : "cat_omr",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes ('Ateliers du Retz Emploi', 'La Ressourcerie de l'ïle', 'Emmaüs', 'Véti Frat', 'La Croix Rouge') récupèrent les anciens jouets. <br/>Voir page 'lieux'.",
	"descr_en" : "Several agencies ('Retz Employment Workshops', 'The Ressourcerie of the island', 'Emmaus', 'Veti Frat', 'The Red Cross') recover old toys. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,jouet",
	"mots_cles_en" : "reuse,toy"
}, {
	"code" : "smco_reempmeuble",
	"nom" : "Réemploi meubles",
	"nom_en" : "Reuse furniture",
	"libelleBouton" : "Réemploi meubles",
	"libelleBouton_en" : "Reuse furniture",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes ('Emmaus', 'Secours Populaire', 'Retz'agir', 'Le comptoir du Solilab') récupèrent les anciens meubles. <br/>Voir page 'lieux'.",
	"descr_en" : "Several organizations (Emmaus' 'Secours Populaire', 'Retz'agir', 'The counter Solilab') recover antique furniture. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,meuble",
	"mots_cles_en" : "re,use,furniture"
}, {
	"code" : "smco_reempvet",
	"nom" : "Réemploi vêtements",
	"nom_en" : "Reuse clothing",
	"libelleBouton" : "Réemploi vêtements",
	"libelleBouton_en" : "Reuse clothing",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes ('Ding-Fring', 'Secours Populaire', ) récupèrent les vêtements. <br/>Voir page 'lieux'.",
	"descr_en" : "Several agencies ('Ding Fring', 'Secours Populaire') recover clothing. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,vetement",
	"mots_cles_en" : "reuse,clothing"
}, {
	"code" : "smco_reempdivers",
	"nom" : "Réemploi Objets divers",
	"nom_en" : "Reuse Miscellaneous objects",
	"libelleBouton" : "Réemploi Objets divers",
	"libelleBouton_en" : "Reuse Miscellaneous objects",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes (associations...) récupèrent les anciens meubles. <br/>Voir page 'lieux'.",
	"descr_en" : "Several organizations (associations ...) recover the antique furniture. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,divers",
	"mots_cles_en" : "reuse,various"
}, {
	"code" : "smco_vaisselle",
	"nom" : "Réemploi Vaisselle",
	"nom_en" : "Reuse Crockery",
	"libelleBouton" : "Réemploi Vaisselle",
	"libelleBouton_en" : "Reuse Crockery",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes (association 'La croix rouge', 'La ressourcerie de l'ïle'..) récupèrent la vaissellee.",
	"descr_en" : "Several organizations ('The red cross', 'La ressourcerie de l'ïle'…) recover the ancient books.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,vaisselle",
	"mots_cles_en" : "reuse,dishes"
}, {
	"code" : "smco_papier",
	"nom" : "Recyclage papier associations.",
	"nom_en" : "Paper recycling associations.",
	"libelleBouton" : "Recyclage papier associations.",
	"libelleBouton_en" : "Paper recycling associations.",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes (association <a href='lieu:stco_reemploi51'>Nantes écologie</a>, <a href='lieu:stco_reemploi47'>La croix rouge</a>...) récupèrent les anciens livres. <br/>Voir page 'lieux'.",
	"descr_en" : "Several organizations (<a href='lieu:stco_reemploi51'> Nantes </a> ecology association, <a href='lieu:stco_reemploi47'> The red cross </a> ...) recover the ancient books. See page <br/> 'places'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "recyclage,papier,association",
	"mots_cles_en" : "recycling,paper,combination"
}, {
	"code" : "smco_vendeurlunette",
	"nom" : "Vendeur lunette",
	"nom_en" : "Seller window",
	"libelleBouton" : "Vendeur lunette",
	"libelleBouton_en" : "Seller window",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes (association 'Lunettes Sans Frontière', les magasins 'Optic 2000',  les magasins 'Krys', 'MEDICO Lions Clubs de France'...) récupère les lunettes (vous trouverez en général des réceptacles en carton dans ces endroits). Ces lunettes sont envoyées dans des pays en développement.",
	"descr_en" : "Several organizations (associations' Glasses Without Borders' stores' Optic 2000 ', stores' Krys'' MEDICO Lions Clubs of France ...) retrieves the glasses (you can find usually cardboard receptacles in these places) . These glasses are sent to developing countries.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "vendeur,lunette",
	"mots_cles_en" : "seller,window"
}, {
	"code" : "smco_reprise",
	"nom" : "Reprise par magasins",
	"nom_en" : "Takeover by stores",
	"libelleBouton" : "Reprise par magasins",
	"libelleBouton_en" : "Takeover by stores",
	"modesCollecte" : "true",
	"descr" : "Vous achetez un appareil neuf, le distributeur est désormais tenu de reprendre  l'ancien à l'achat ou la livraison. C'est le principe de la reprise « un pour un ».  ",
	"descr_en" : "You buy a new appliance, the distributor is now required to take the former for the purchase or delivery. This is the principle of the recovery 'one for one'.",
	"cons" : "cons_ecopart",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reprise,magasin",
	"mots_cles_en" : "recovery,store"
}, {
	"code" : "smco_vendeurcassevoiture",
	"nom" : "Casse automobile",
	"nom_en" : "Car breakers",
	"libelleBouton" : "Casse automobile",
	"libelleBouton_en" : "Car breakers",
	"modesCollecte" : "true",
	"descr" : "Les casses automobile ('fourrières') récupèrent les anciens véhicules.",
	"descr_en" : "The car breaks ('headland') recover older vehicles.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "casse,automobile",
	"mots_cles_en" : "car,breakers"
}, {
	"code" : "smco_velo",
	"nom" : "Réemploi  vélos",
	"nom_en" : "Reuse bike",
	"libelleBouton" : "Réemploi  vélos",
	"libelleBouton_en" : "Reuse bike",
	"modesCollecte" : "true",
	"descr" : "Plusieurs organismes (associations <a href='lieu:stco_reemploi14'>ATAO</a>,  <a href='lieu:stco_reemploi14'>Place aux vélos</a>,  <a href='lieu:stco_reemploiajout2'>Transformeur</a>, Vélo Campus) récupèrent les anciens vélos.",
	"descr_en" : "Several organizations (associations <a href='lieu:stco_reemploi14'> ATAO </a> <a href='lieu:stco_reemploi14'> Place </a> bikes <a href='lieu:stco_reemploiajout2'> Transformer < / a>, Bicycle Campus) recover old bikes.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "reemploi,velos",
	"mots_cles_en" : "reuse,bicycle"
}, {
	"code" : "smco_pharmacie",
	"nom" : "Pharmacie",
	"nom_en" : "Pharmacy",
	"libelleBouton" : "Pharmacie",
	"libelleBouton_en" : "Pharmacy",
	"modesCollecte" : "true",
	"descr" : "Les pharmacies ont l'obligation de récupérer les anciens médicaments, avec ou sans conditionnement. <br/>Voir fiche 'Médicaments'.",
	"descr_en" : "Pharmacies have the obligation to recover the older drugs, with or without conditioning. More details <br/> 'Drugs'.",
	"image" : "reemploi_petit.png",
	"mots_cles" : "pharmacie",
	"mots_cles_en" : "pharmacy"
}, {}];
