var _garbagesDatas = [{
			"code" : "dec_acides",
			"type" : "Déchet",
			"nom" : "Acides",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "acide, base, produit chimique",
			"mots_cles" : "acide, base, produit chimique",
			"cons" : "cons_toxique",
			"image" : "bouteille_acide_chlorhydrique_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_aerosols",
			"type" : "Déchet",
			"nom" : "Aérosols",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "aérosol, bombe aérosol, déodorant, laque",
			"mots_cles" : "aerosol, bombe aerosol, deodorant, laque",
			"cons" : "cons_sansbouchon,cons_bouchonamour,cons_ferraille,cons_acier",
			"image" : "aerosol_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_agenda",
			"type" : "Déchet",
			"nom" : "Agenda",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "acide,agenda",
			"mots_cles" : "acide,agenda",
			"image" : "agenda_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_ampouleBasseConso",
			"type" : "Déchet",
			"nom" : "Ampoule basse consommation",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_ampouleseco",
			"descr" : "ampoule basse consommation, ampoule à économie d'énergie, lampe à économie d'énergie",
			"mots_cles" : "ampoule basse consommation, ampoule a economie denergie, lampe a economie denergie",
			"cons" : "cons_ampoulemercure,cons_recuppdv2,",
			"image" : "ampoules_basse_consommation_mini.png",
			"modco" : "modco_pointsdevente",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_ampouleClassique",
			"type" : "Déchet",
			"nom" : "Ampoule classique",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "ampoule classique, ampoule à incandescence",
			"mots_cles" : "ampoule classique, ampoule a incandescence",
			"image" : "ampoule_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_annuaire",
			"type" : "Déchet",
			"nom" : "Annuaire",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "annuaire",
			"mots_cles" : "annuaire",
			"image" : "annuaire_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_antiFourmis",
			"type" : "Déchet",
			"nom" : "Anti-fourmis",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "anti-fourmis",
			"mots_cles" : "anti fourmis",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/antifourmi_jardinbio_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_antigel",
			"type" : "Déchet",
			"nom" : "Antigel",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "antigel",
			"mots_cles" : "antigel",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/antigel_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_appareilElectronique",
			"type" : "Déchet",
			"nom" : "Appareil électronique",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "appareil électronique,outillage alimenté par électricit",
			"mots_cles" : "appareil electronique,outillage alimente par electricit",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "images_non_libres_temp/outillage_electrique_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_appareilsChauffant",
			"type" : "Déchet",
			"nom" : "Appareil chauffant",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "appareil chauffant, appareil de chauffage, chauffage, appareil de cuisson, four",
			"mots_cles" : "appareil chauffant, appareilchauffage, chauffage, appareilcuisson, four",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "chauffage_soufflant_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_appareilsElectromenager",
			"type" : "Déchet",
			"nom" : "Appareil électroménager",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_encombrant",
			"descr" : "appareil électroménager,petit électroménager",
			"mots_cles" : "appareil electromenager,petit electromenager",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "machine_a_cafe_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_barilLessive",
			"type" : "Déchet",
			"nom" : "Baril lessive",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "baril de lessive, paquets de lessives, barils en carton",
			"mots_cles" : "barillessive, paquetslessives, barils en carton",
			"image" : "baril_lessive_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_barquetteAluminium",
			"type" : "Déchet",
			"nom" : "Barquette aluminium",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_allu",
			"descr" : "barquette aluminium, barquette pizza, barquette quiche",
			"mots_cles" : "barquette aluminium, barquette pizza, barquette quiche",
			"cons" : "cons_allu",
			"image" : "barquette_aluminium_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_barquettePolystyrene",
			"type" : "Déchet",
			"nom" : "Barquette polystyrène",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "barquette polystyrène, barquette plastique",
			"mots_cles" : "barquette polystyrene, barquette plastique",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "barquette_polystyrene_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_batteriesVoiture",
			"type" : "Déchet",
			"nom" : "Batteries voiture",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_batterie",
			"descr" : "batteries de voiture",
			"mots_cles" : "batteriesvoiture",
			"cons" : "cons_toxique",
			"image" : "batterie_voiture_mini.png",
			"modco" : "smco_garage,modco_decheterie,modco_ecopoint",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bidonDHuileMoteurVide",
			"type" : "Déchet",
			"nom" : "Bidon d'huile moteur vide",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_omr",
			"descr" : "bidon d'huile moteur vide",
			"mots_cles" : "bidon dhuile moteur vide",
			"image" : "huile_moteur_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bidonMetal",
			"type" : "Déchet",
			"nom" : "Bidon métal vide",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "bidon de métal vide",
			"mots_cles" : "bidonmetal vide",
			"cons" : "cons_ferraille,cons_acier",
			"image" : "bidon_metal_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bocalEnVerre",
			"type" : "Déchet",
			"nom" : "Bocal verre",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verre",
			"descr" : "bocal en verre, nutella, pâte a tartiner, pot en verre",
			"mots_cles" : "bocal en verre, nutella, pate a tartiner, pot en verre",
			"cons" : "cons_sansbouchon,cons_couverclemetal,cons_potsmoutarde,cons_verre",
			"image" : "bocal_verre_mini.png",
			"modco" : "modco_contverre,modco_decheterie,modco_ecopoint",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_boiteAOeufsEnPlastique",
			"type" : "Déchet",
			"nom" : "Boîte à œufs plastique",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "boîte à œufs en plastique",
			"mots_cles" : "boite a œufs en plastique",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "boite_a_oeufs_plastique_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_boiteCamembertEnBois",
			"type" : "Déchet",
			"nom" : "Boîte camembert bois",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_omr",
			"descr" : "boîte camembert en bois",
			"mots_cles" : "boite camembert en bois",
			"image" : "boite_camembert_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_boiteConserve",
			"type" : "Déchet",
			"nom" : "Boîte conserve",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "boîte de conserve, conserve",
			"mots_cles" : "boiteconserve, conserve",
			"cons" : "cons_ferraille,cons_acier",
			"image" : "conserve_ratatouille_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_boiteMetallique",
			"type" : "Déchet",
			"nom" : "Boite métallique",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "boite métallique",
			"mots_cles" : "boite metallique",
			"cons" : "cons_ferraille,cons_acier",
			"image" : "boite_metal_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_boiteOeufsEnCarton",
			"type" : "Déchet",
			"nom" : "Boîte œufs carton",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "boîte à œufs en carton",
			"mots_cles" : "boite a œufs en carton",
			"image" : "boite_a_oeufs_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bombeMousseARaser",
			"type" : "Déchet",
			"nom" : "Bombe mousse à raser",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "bombe mousse à raser",
			"mots_cles" : "bombe mousse a raser",
			"cons" : "cons_sansbouchon,cons_ferraille,cons_acier",
			"image" : "mousse_a_raser_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bombePeinture",
			"type" : "Déchet",
			"nom" : "Bombe peinture",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "bombe de peinture, peinture aérosol",
			"mots_cles" : "bombepeinture, peinture aerosol",
			"cons" : "cons_sansbouchon,cons_pastoxique,cons_toxique",
			"image" : "peinture_aerosol_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouchonLiege",
			"type" : "Déchet",
			"nom" : "Bouchon liège",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "bouchon de liège",
			"mots_cles" : "bouchonliege",
			"cons" : "cons_bouchonliege,",
			"image" : "bouchon_liege_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouchonPlastique",
			"type" : "Déchet",
			"nom" : "Bouchon plastique",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "bouchon plastique, bouchon plastique",
			"mots_cles" : "bouchon plastique, bouchon plastique",
			"cons" : "cons_bouchonamour,",
			"image" : "bouchon_plastique_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bougie",
			"type" : "Déchet",
			"nom" : "Bougie",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "bougie",
			"mots_cles" : "bougie",
			"image" : "images_non_libres_temp/bougie_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "07/2015"
		}, {
			"code" : "dec_bouteilleDhuileAlimentaire",
			"type" : "Déchet",
			"nom" : "Bouteille d'huile",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "bouteille d'huile, bouteille d'eau",
			"mots_cles" : "bouteille dhuile, bouteille deau",
			"cons" : "cons_bouchon,cons_bouchonamour,",
			"image" : "grande_bouteille_huile_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteilleDhuileEnVerre",
			"type" : "Déchet",
			"nom" : "Bouteille d'huile verre",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verre",
			"descr" : "bouteille d'huile en verre",
			"mots_cles" : "bouteille dhuile en verre",
			"cons" : ",cons_sansbouchon,cons_verre",
			"image" : "bouteille_huile_olive_mini.png",
			"modco" : "modco_contverre,modco_decheterie,modco_ecopoint",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteilleGaz",
			"type" : "Déchet",
			"nom" : "Bouteille de gaz",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_ddm_gros",
			"descr" : "bouteille de gaz",
			"mots_cles" : "bouteillegaz",
			"cons" : "cons_toxique",
			"image" : "bouteille_gaz_mini.png",
			"modco" : "modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"commentaires" : "faq_fiche_lombricompost",
			"src" : "MieuxTrierANantes 12/2014"
		}, {
			"code" : "dec_bouteilleLait",
			"type" : "Déchet",
			"nom" : "Bouteille lait",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "bouteille de lait",
			"mots_cles" : "bouteillelait",
			"cons" : "cons_bouchon,cons_bouchonamour,cons_capsulelait,",
			"image" : "bouteille_lait_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteillePlastique",
			"type" : "Déchet",
			"nom" : "Bouteille plastique",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "bouteille en plastique, bouteille de soda",
			"mots_cles" : "bouteille en plastique, bouteillesoda",
			"cons" : "cons_bouchon,cons_bouchonamour,",
			"image" : "bouteille_transparente_mini.png",
			"image_secondaire" : "ketchup_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteilleProduitMenagerNonVide",
			"type" : "Déchet",
			"nom" : "Bouteille produit ménager non vide",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "bouteille produit ménager non vide",
			"mots_cles" : "bouteille produit menager non vide",
			"cons" : "cons_bouchon,cons_bouchonamour,cons_pasuniquementbouteilleflacon",
			"image" : "images_non_libres_temp/bouteille_produit_menager_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteilleProduitMenagerVide",
			"type" : "Déchet",
			"nom" : "Bouteille produit ménager vide",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "bouteille produit ménager vide",
			"mots_cles" : "bouteille produit menager vide",
			"cons" : "cons_bouchon,cons_bouchonamour,",
			"image" : "images_non_libres_temp/bouteille_produit_menager_vide_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteillesSirop",
			"type" : "Déchet",
			"nom" : "Bouteilles sirop (métal)",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "bouteilles de sirop (métal)",
			"mots_cles" : "bouteillessirop metal",
			"cons" : "cons_bouchon,cons_bouchonamour,cons_ferraille,cons_acier",
			"image" : "bouteille_sirop_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_bouteilleVerre",
			"type" : "Déchet",
			"nom" : "Bouteille verre",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verre",
			"descr" : "bouteille en verre, bouteille de vin, bouteille de bière",
			"mots_cles" : "bouteille en verre, bouteillevin, bouteillebiere",
			"cons" : "cons_sansbouchon,cons_verre",
			"image" : "bouteille_mini.png",
			"modco" : "modco_contverre,modco_decheterie,modco_ecopoint",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_branchage",
			"type" : "Déchet",
			"nom" : "Branchage feuillage",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_organiquegros",
			"descr" : "branchage, feuillage, taille d'arbre",
			"mots_cles" : "branchage, feuillage, taille darbre",
			"cons" : "cons_compostage",
			"image" : "feuillages_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_compostage",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 12/2014"
		}, {
			"code" : "dec_briqueAlimentaire",
			"type" : "Déchet",
			"nom" : "Brique alimentaire",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_ela",
			"descr" : "brique alimentaire, brique de lait, tétra pack",
			"mots_cles" : "brique alimentaire, briquelait, tetra pack",
			"cons" : "bouchon_brique,cons_tetrapak,cons_bouchon,cons_bouchonamour,",
			"image" : "brique_alimentaire_mini.png",
			"modco" : "modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cagetteBois",
			"type" : "Déchet",
			"nom" : "Cagette bois",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_omr",
			"descr" : "cagette bois, cageot",
			"mots_cles" : "cagette bois, cageot",
			"image" : "cagette_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cahier",
			"type" : "Déchet",
			"nom" : "Cahier",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "cahier, cahier, bloc notes (sans spirale), carnet",
			"mots_cles" : "cahier, cahier, bloc notes sans spirale, carnet",
			"image" : "bloc_note_mini.png",
			"image_secondaire" : "cahier_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_calendrier",
			"type" : "Déchet",
			"nom" : "Calendrier",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "calendrier",
			"mots_cles" : "calendrier",
			"image" : "calendrier_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_canetteSoda",
			"type" : "Déchet",
			"nom" : "Canette soda",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_acier",
			"descr" : "canette de soda",
			"mots_cles" : "canettesoda",
			"cons" : "cons_ferraille,cons_acier",
			"image" : "cannette_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_capsuleCafe",
			"type" : "Déchet",
			"nom" : "capsule café",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_omr",
			"descr" : "capsule de café, capsule métal ou plastique dosette café",
			"mots_cles" : "capsulecafe, capsule metal ou plastique dosette cafe",
			"cons" : "cons_nespresso,cons_trop_petit,",
			"image" : "dosette_cafe_plastique_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cartePostale",
			"type" : "Déchet",
			"nom" : "Carte postale",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "carte postale",
			"mots_cles" : "carte postale",
			"image" : "carte_postale_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cartonPetitsOuGrands",
			"type" : "Déchet",
			"nom" : "Carton (petits ou grands)",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "carton (petits ou grands)",
			"mots_cles" : "carton petits ou grands",
			"image" : "carton_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cartouchesEncres",
			"type" : "Déchet",
			"nom" : "Cartouches encres",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_cartouche",
			"descr" : "cartouches encres",
			"mots_cles" : "cartouches encres",
			"image" : "cartouches_imprimantes_mini.png",
			"modco" : "modco_pointsdevente,modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cdDvdK7",
			"type" : "Déchet",
			"nom" : "CD/DVD/K7",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "CD/DVD/K7, cassette audio, cassette vidéo",
			"mots_cles" : "cd/dvd/k7, cassette audio, cassette video",
			"image" : "cd_sansemballage_mini.png",
			"image_secondaire" : "pochette_cd_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_chaussureEnBonEtat",
			"type" : "Déchet",
			"nom" : "Chaussure bon état",
			"cat_usuel" : "cu_vetementtissu",
			"cat_trait" : "cat_vetement",
			"descr" : "chaussure en bon état, bote en bon état",
			"mots_cles" : "chaussure en bon etat, bote en bon etat",
			"image" : "chaussures_mini.png",
			"modco" : "smco_conteneurlerelais,smco_reempvet,modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_chaussuresUsagees",
			"type" : "Déchet",
			"nom" : "Chaussures usagées",
			"cat_usuel" : "cu_vetementtissu",
			"cat_trait" : "cat_omr",
			"descr" : "chaussures usagées, bote usagée, chaussure en mauvais état",
			"mots_cles" : "chaussures usagees, bote usagee, chaussure en mauvais etat",
			"image" : "images_non_libres_temp/chaussures_usagees_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cigarette",
			"type" : "Déchet",
			"nom" : "Cigarette",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "cigarette, mégot, cigare",
			"mots_cles" : "cigarette, megot, cigare",
			"image" : "megot_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_classeur",
			"type" : "Déchet",
			"nom" : "Classeur",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_omr",
			"descr" : "classeur",
			"mots_cles" : "classeur",
			"image" : "classeur_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_colles",
			"type" : "Déchet",
			"nom" : "Colles",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "colles",
			"mots_cles" : "colles",
			"cons" : "cons_toxique",
			"image" : "colle_a_bois_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_congelateurs",
			"type" : "Déchet",
			"nom" : "congélateurs",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "congélateurs",
			"mots_cles" : "congelateurs",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "congelateur_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cotonTige",
			"type" : "Déchet",
			"nom" : "Coton tige",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "coton tige",
			"mots_cles" : "coton tige",
			"image" : "cotons_tiges_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_coucheBebe",
			"type" : "Déchet",
			"nom" : "Couche bébé",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "couche bébé",
			"mots_cles" : "couche bebe",
			"cons" : "cons_dec_coucheBebe,",
			"image" : "couche_bebe_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"commentaires" : "faq_modco_contmpb",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_couverclePotEnVerre",
			"type" : "Déchet",
			"nom" : "Couvercle métallique",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_omr",
			"descr" : "couvercle de pot en verre, couvercle métallique, capsule bière",
			"mots_cles" : "couverclepot en verre, couvercle metallique, capsule biere",
			"cons" : "cons_trop_petit,",
			"image" : "couvercle_bocal_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_couverts",
			"type" : "Déchet",
			"nom" : "Couverts",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_omr",
			"descr" : "couverts, couteau, cuillère, fourchette",
			"mots_cles" : "couverts, couteau, cuillere, fourchette",
			"image" : "fourchette_mini.png",
			"image_secondaire" : "couteau_mini.png, cuillere_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cremeEnTube",
			"type" : "Déchet",
			"nom" : "Crème en tube",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr",
			"descr" : "crème en tube",
			"mots_cles" : "creme en tube",
			"image" : "creme_main_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_cremeEtDentifriceTube",
			"type" : "Déchet",
			"nom" : "Crème et dentifrice (tube)",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "crème et dentifrice (tube), crème en tube, tube de dentifrice",
			"mots_cles" : "creme et dentifrice tube, creme en tube, tubedentifrice",
			"cons" : "cons_bouchonamour,",
			"image" : "dentifrice_mini.png",
			"image_secondaire" : "creme_main_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_deboucheurLiquide",
			"type" : "Déchet",
			"nom" : "Déboucheur liquide",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "déboucheur liquide",
			"mots_cles" : "deboucheur liquide",
			"cons" : "cons_toxique",
			"image" : "desinfectant_toilette_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_deodorantStick",
			"type" : "Déchet",
			"nom" : "Déodorant stick",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "déodorant stick, déodorant à bille",
			"mots_cles" : "deodorant stick, deodorant a bille",
			"image" : "stick_deodorant.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 01/2015"
		}, {
			"code" : "dec_detachant",
			"type" : "Déchet",
			"nom" : "Détachant",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "détachant (c'est un produit toxique)",
			"mots_cles" : "detachant cest un produit toxique",
			"cons" : "cons_pasbouchonamour,cons_toxique",
			"image" : "detacheur_universel_vetement_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_eauJavel",
			"type" : "Déchet",
			"nom" : "Eau Javel",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "eau de Javel",
			"mots_cles" : "eaujavel",
			"cons" : "cons_pasbouchonamour,cons_toxique",
			"image" : "bouteille_eau_de_javel_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_emballagesEnCartonPlat",
			"type" : "Déchet",
			"nom" : "Emballages carton plat",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "emballages en carton plat, Suremballage carton, cartonnette, boîte de céréales, boîte à pizza",
			"mots_cles" : "emballages en carton plat, suremballage carton, cartonnette, boitecereales, boite a pizza",
			"cons" : "cons_souille,",
			"image" : "cartonette_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_engraisChimiques",
			"type" : "Déchet",
			"nom" : "Engrais chimiques",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "engrais chimiques",
			"mots_cles" : "engrais chimiques",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/engrais_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_enveloppe",
			"type" : "Déchet",
			"nom" : "Enveloppe",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "enveloppe",
			"mots_cles" : "enveloppe",
			"cons" : "cons_fenetre_enveloppe,",
			"image" : "enveloppes_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_epeluchuresRestesRepas",
			"type" : "Déchet",
			"nom" : "Épluchures / restes repas",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_organique",
			"descr" : "épluchures / restes de repas, épluchures, restes de repas, nourriture",
			"mots_cles" : "epluchures / restesrepas, epluchures, restesrepas, nourriture",
			"cons" : "cons_compostage",
			"image" : "epeluchure_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_compostage",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_equipementsAudioEtVideo",
			"type" : "Déchet",
			"nom" : "Équipements audio et vidéo",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "équipements audio et vidéo",
			"mots_cles" : "equipements audio et video",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "chaine_hifi_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "www"
		}, {
			"code" : "dec_essenceTerebenthine",
			"type" : "Déchet",
			"nom" : "Essence térébenthine",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "essence de térébenthine",
			"mots_cles" : "essenceterebenthine",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/essence_therebentine_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_essuiToutRouleauCarton",
			"type" : "Déchet",
			"nom" : "Essuie-tout (rouleau carton)",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "essuie-tout (rouleau carton), rouleau carton papier toilette",
			"mots_cles" : "essuie tout rouleau carton, rouleau carton papier toilette",
			"image" : "rouleau_carton_essui_tout_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_essuiToutSaufRouleauCarton",
			"type" : "Déchet",
			"nom" : "Essuie-tout (sauf rouleau carton)",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_omr",
			"descr" : "essuie-tout (sauf rouleau carton), sopalin, papier absorbant, papier toilette",
			"mots_cles" : "essuie tout sauf rouleau carton, sopalin, papier absorbant, papier toilette",
			"cons" : "cons_souille,",
			"image" : "essui_tout_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_filmPlastique",
			"type" : "Déchet",
			"nom" : "Film plastique",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "film plastique",
			"mots_cles" : "film plastique",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "film_plastique_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_filmsPhotographiques",
			"type" : "Déchet",
			"nom" : "Films photographiques",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "films photographiques, diapositive, pellicule",
			"mots_cles" : "films photographiques, diapositive, pellicule",
			"cons" : "cons_toxique",
			"image" : "films_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_filtreAHuile",
			"type" : "Déchet",
			"nom" : "Filtre à huile",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "filtre à huile",
			"mots_cles" : "filtre a huile",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/filtre_huile_petit.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_flaconProduitsDentretien",
			"type" : "Déchet",
			"nom" : "Flacon de produits d'entretien",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "flacon de produits d'entretien, Flacon produit ménager vide, flacon de produits d'entretien",
			"mots_cles" : "flaconproduits dentretien, flacon produit menager vide, flaconproduits dentretien",
			"cons" : "cons_bouchon,cons_bouchonamour,",
			"image" : "bouteille_white_spirit_mini.png",
			"image_secondaire" : "bouteille_pec_citron_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_flaconSavon",
			"type" : "Déchet",
			"nom" : "Flacon savon",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_emr",
			"descr" : "flacon de savon, Flacon en plastique, flacon de savon",
			"mots_cles" : "flaconsavon, flacon en plastique, flaconsavon",
			"cons" : "cons_bouchon,cons_bouchonamour,",
			"image" : "flacon_savon_mini.png",
			"image_secondaire" : "bouteille_savon_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_fongicides",
			"type" : "Déchet",
			"nom" : "Fongicide",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "fongicide",
			"mots_cles" : "fongicide",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/fongicide_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_fournituresHorsPapier",
			"type" : "Déchet",
			"nom" : "Fournitures (hors papier)",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "fournitures (hors papier), fournitures de bureau, crayon, stylo, feutre, gomme, agrafeuse, règle, compas, pochette plastique, classeur, trombone, taille-crayon, ciseaux",
			"mots_cles" : "fournitures hors papier, fournituresbureau, crayon, stylo, feutre, gomme, agrafeuse, regle, compas, pochette plastique, classeur, trombone, taille crayon, ciseaux",
			"image" : "crayon_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_gazon",
			"type" : "Déchet",
			"nom" : "Gazon",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_organiquegros",
			"descr" : "gazon, pelouse, herbe",
			"mots_cles" : "gazon, pelouse, herbe",
			"cons" : "cons_compostage",
			"image" : "pelouse_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_compostage",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_gravat",
			"type" : "Déchet",
			"nom" : "Gravât",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_materiaux",
			"descr" : "gravât",
			"mots_cles" : "gravat",
			"cons" : "cons_paspoubelle",
			"image" : "gravat_mini.png",
			"modco" : "modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_grillage",
			"type" : "Déchet",
			"nom" : "Grillage",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_encombrant",
			"descr" : "grillage, clôture",
			"mots_cles" : "grillage, cloture",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "grillage_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_guitare",
			"type" : "Déchet",
			"nom" : "Guitare",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_instrument",
			"descr" : "guitare",
			"mots_cles" : "guitare",
			"image" : "guitare_mini.png",
			"modco" : "smco_reempdivers,modco_decheterie,modco_ecopoint,modco_encombrant",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_herbicides",
			"type" : "Déchet",
			"nom" : "Herbicide",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "herbicide, désherbant",
			"mots_cles" : "herbicide, desherbant",
			"cons" : "cons_toxique",
			"image" : "desherbant_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_huileMinerale",
			"type" : "Déchet",
			"nom" : "Huile moteur",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "huile minérale,huile voiture,huile moteur",
			"mots_cles" : "huile minerale,huile voiture,huile moteur",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/huile_minerale_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_huileVidange",
			"type" : "Déchet",
			"nom" : "Huile vidange",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "huile de vidange",
			"mots_cles" : "huilevidange",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/huile_vidange_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_insecticides",
			"type" : "Déchet",
			"nom" : "Insecticides",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "insecticides",
			"mots_cles" : "insecticides",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/fongicide_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_jouetsAlimentesParElectricite",
			"type" : "Déchet",
			"nom" : "Jouet alimenté par électricité",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_jouetpile",
			"descr" : "jouet alimenté par électricité, jeu avec pile, train électrique",
			"mots_cles" : "jouet alimente par electricite, jeu avec pile, train electrique",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "jeu_enfant_avec_pile_mini.png",
			"modco" : "smco_reempjouet,modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_jouetsNonElectroniques",
			"type" : "Déchet",
			"nom" : "Jouet non électronique",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_jouet",
			"descr" : "jouet non électronique, jeu, peluche, poupée, petite voiture",
			"mots_cles" : "jouet non electronique, jeu, peluche, poupee, petite voiture",
			"image" : "petite_voiture_mini.png",
			"image_secondaire" : "jouet_enfant_mini.png",
			"modco" : "smco_reempjouet,modco_bacbleu,modco_sacbleu",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_journal",
			"type" : "Déchet",
			"nom" : "Journal",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "journal, revue",
			"mots_cles" : "journal, revue",
			"image" : "journal_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_laine",
			"type" : "Déchet",
			"nom" : "Laine",
			"cat_usuel" : "cu_vetementtissu",
			"cat_trait" : "cat_vetement",
			"descr" : "laine",
			"mots_cles" : "laine",
			"image" : "pelotes_laine_mini.png",
			"image_secondaire" : "images_non_libres_temp/bouteille_produit_menager_mini.png",
			"modco" : "smco_conteneurlerelais,smco_reempvet,modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_laineVerre",
			"type" : "Déchet",
			"nom" : "Laine de verre",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_materiaux",
			"descr" : "laine de verre, laine de verre, laine de roche",
			"mots_cles" : "laineverre, laineverre, laineroche",
			"cons" : "cons_paspoubelle",
			"image" : "laine_roche_mini.png",
			"image_secondaire" : "images_non_libres_temp/bouteille_produit_menager_vide_mini.png",
			"modco" : "modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_lampe",
			"type" : "Déchet",
			"nom" : "Lampe",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "lampe",
			"mots_cles" : "lampe",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "lampe_chevet_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_lingette",
			"type" : "Déchet",
			"nom" : "Lingette",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "lingette",
			"mots_cles" : "lingette",
			"image" : "lingette_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_liquideRefroidissement",
			"type" : "Déchet",
			"nom" : "Liquide refroidissement",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "liquide de refroidissement",
			"mots_cles" : "liquiderefroidissement",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/liquide_refroidissement_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_litierePourAnimaux",
			"type" : "Déchet",
			"nom" : "Litière pour animaux",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "litière pour animaux",
			"mots_cles" : "litiere pour animaux",
			"image" : "images_non_libres_temp/litiere_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_livre",
			"type" : "Déchet",
			"nom" : "Livre",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "livre",
			"mots_cles" : "livre",
			"image" : "livre_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_lunette",
			"type" : "Déchet",
			"nom" : "Lunette",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_lunette",
			"descr" : "lunette",
			"mots_cles" : "lunette",
			"image" : "lunette_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,smco_vendeurlunette",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_magazine",
			"type" : "Déchet",
			"nom" : "Magazine",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "magazine, revue",
			"mots_cles" : "magazine, revue",
			"image" : "magazines_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_masticCarrosserie",
			"type" : "Déchet",
			"nom" : "Mastic carrosserie",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "mastic de carrosserie",
			"mots_cles" : "masticcarrosserie",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/mastic_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_matelas",
			"type" : "Déchet",
			"nom" : "Matelas",
			"cat_usuel" : "cu_vetementtissu",
			"cat_trait" : "cat_encombrant",
			"descr" : "matelas",
			"mots_cles" : "matelas",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "matelas_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_medicaments",
			"type" : "Déchet",
			"nom" : "Médicament",
			"cat_usuel" : "scu_medicament",
			"cat_trait" : "cat_medicament",
			"descr" : "médicament",
			"mots_cles" : "medicament",
			"cons" : "cons_recupmedicament,",
			"image" : "medicaments_mini.png",
			"modco" : "smco_pharmacie,modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_meuble",
			"type" : "Déchet",
			"nom" : "Meuble",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_encombrant",
			"descr" : "meuble",
			"mots_cles" : "meuble",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "canape_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_miroir",
			"type" : "Déchet",
			"nom" : "Miroir",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "miroir",
			"mots_cles" : "miroir",
			"cons" : "cons_verre",
			"image" : "miroir_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"commentaires" : "faq_pb_plastique",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_moquette",
			"type" : "Déchet",
			"nom" : "Moquette",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "moquette",
			"mots_cles" : "moquette",
			"image" : "moquette_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_mortAuxRats",
			"type" : "Déchet",
			"nom" : "Mort aux rats",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "mort aux rats, raticide ",
			"mots_cles" : "mort aux rats, raticide ",
			"cons" : "cons_toxique",
			"image" : "mortaurat_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_mouchoir",
			"type" : "Déchet",
			"nom" : "Mouchoir",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "mouchoir",
			"mots_cles" : "mouchoir",
			"cons" : "cons_souille,",
			"image" : "mouchoirs_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_naphtaline",
			"type" : "Déchet",
			"nom" : "Naphtaline",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "naphtaline, antimite",
			"mots_cles" : "naphtaline, antimite",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/naphtaline_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_neons",
			"type" : "Déchet",
			"nom" : "Néon",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ampouleseco",
			"descr" : "néon",
			"mots_cles" : "neon",
			"image" : "neon_mini.png",
			"modco" : "modco_pointsdevente",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_nettoyantsALAmmoniac",
			"type" : "Déchet",
			"nom" : "Nettoyant à l'ammoniac",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "nettoyant à l'ammoniac",
			"mots_cles" : "nettoyant a lammoniac",
			"cons" : "cons_toxique",
			"image" : "bouteille_ammoniaque_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_nettoyantsCuivreEtArgenterie",
			"type" : "Déchet",
			"nom" : "Nettoyants cuivre et argenterie",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "nettoyants cuivre et argenterie",
			"mots_cles" : "nettoyants cuivre et argenterie",
			"cons" : "cons_toxique",
			"image" : "nettoyant_cuivre_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_objetEnTerreCuite",
			"type" : "Déchet",
			"nom" : "Objet terre cuite",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "objet en terre cuite",
			"mots_cles" : "objet en terre cuite",
			"cons" : "cons_verre",
			"image" : "terre_cuite_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_ordinateursPortables",
			"type" : "Déchet",
			"nom" : "Ordinateurs portables",
			"cat_usuel" : "scu_medicament",
			"cat_trait" : "cat_d3e",
			"descr" : "ordinateurs portables",
			"mots_cles" : "ordinateurs portables",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "ordi_portable_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_outilsBricolageOuJardinage",
			"type" : "Déchet",
			"nom" : "outils bricolage ou jardinage",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "outils bricolage ou jardinage, marteau, tournevis, cisaille, scie, râteau, hache",
			"mots_cles" : "outils bricolage ou jardinage, marteau, tournevis, cisaille, scie, rateau, hache",
			"image" : "tournevis_mini.png",
			"image_secondaire" : "marteau_2_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_papier",
			"type" : "Déchet",
			"nom" : "Papier",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "papier, prospectus, publicité, feuille (imprimée ou non)",
			"mots_cles" : "papier, prospectus, publicite, feuille imprimee ou non",
			"image" : "feuilles_petit_2.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_papierAluminium",
			"type" : "Déchet",
			"nom" : "Papier aluminium",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_omr",
			"descr" : "papier aluminium",
			"mots_cles" : "papier aluminium",
			"cons" : "cons_papieralu,",
			"image" : "papier_alu_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_papierCadeau",
			"type" : "Déchet",
			"nom" : "Papier cadeau",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_omr",
			"descr" : "papier cadeau",
			"mots_cles" : "papier cadeau",
			"image" : "papier_cadeau_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"commentaires" : "faq_papierparticulier",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_papierPeint",
			"type" : "Déchet",
			"nom" : "Papier peint",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_omr",
			"descr" : "papier peint, crépon",
			"mots_cles" : "papier peint, crepon",
			"image" : "papier_peint_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"commentaires" : "faq_papierparticulier",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_parpaing",
			"type" : "Déchet",
			"nom" : "Parpaing",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_materiaux",
			"descr" : "parpaing",
			"mots_cles" : "parpaing",
			"cons" : "cons_paspoubelle",
			"image" : "parpaing_mini.png",
			"modco" : "modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_peintureAntirouille",
			"type" : "Déchet",
			"nom" : "Peinture antirouille",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "peinture antirouille",
			"mots_cles" : "peinture antirouille",
			"cons" : "cons_pastoxique,cons_toxique",
			"image" : "images_non_libres_temp/antirouille_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_peinturesHuileEtEau",
			"type" : "Déchet",
			"nom" : "Peinture huile et eau",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "peinture huile et eau",
			"mots_cles" : "peinture huile et eau",
			"cons" : "cons_toxique",
			"image" : "peinture_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_peripheriquesInformatiques",
			"type" : "Déchet",
			"nom" : "Périphériques informatiques",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_info",
			"descr" : "périphériques informatiques, écran, clavier, souris, imprimante",
			"mots_cles" : "peripheriques informatiques, ecran, clavier, souris, imprimante",
			"image" : "clavier_ordi_mini.png",
			"image_secondaire" : "souris_mini.png",
			"modco" : "smco_reempinfo,modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_piano",
			"type" : "Déchet",
			"nom" : "Piano",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_instrument",
			"descr" : "piano",
			"mots_cles" : "piano",
			"image" : "images_non_libres_temp/piano_mini.png",
			"modco" : "smco_reempdivers,modco_decheterie,modco_ecopoint,modco_encombrant",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_piles",
			"type" : "Déchet",
			"nom" : "Piles",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_pile",
			"descr" : "piles, petits accumulateurs",
			"mots_cles" : "piles, petits accumulateurs",
			"cons" : "cons_pilerechargeable,cons_recuppdv2,",
			"image" : "pile_45_mini.png",
			"image_secondaire" : "pile9v_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_pointsdevente",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 12/2014"
		}, {
			"code" : "dec_plancheBois",
			"type" : "Déchet",
			"nom" : "Planche bois",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_materiaux",
			"descr" : "planche de bois",
			"mots_cles" : "planchebois",
			"cons" : "cons_paspoubelle",
			"image" : "planche_bois_mini.png",
			"image_secondaire" : "morceaux_de_bois_mini.png",
			"modco" : "modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_plante",
			"type" : "Déchet",
			"nom" : "Plante",
			"cat_usuel" : "cu_vertbois",
			"cat_trait" : "cat_organiquegros",
			"descr" : "plante",
			"mots_cles" : "plante",
			"cons" : "cons_compostage",
			"image" : "plante_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,modco_compostage",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_pneu",
			"type" : "Déchet",
			"nom" : "Pneu",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_encombrant",
			"descr" : "pneu",
			"mots_cles" : "pneu",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "pneu_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_polystyrene",
			"type" : "Déchet",
			"nom" : "Polystyrène",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "polystyrène, barquette de polystyrène",
			"mots_cles" : "polystyrene, barquettepolystyrene",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "polystyrene_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_porcelaine",
			"type" : "Déchet",
			"nom" : "Porcelaine",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "porcelaine, vase",
			"mots_cles" : "porcelaine, vase",
			"cons" : "cons_verre",
			"image" : "vase_mini.png",
			"image_secondaire" : "theiere_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"commentaires" : "faq_pb_plastique",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_potCremeFraîche",
			"type" : "Déchet",
			"nom" : "Pot crème fraîche",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "pot de crème fraîche",
			"mots_cles" : "potcreme fraiche",
			"cons" : "cons_bouchonamour,cons_pasuniquementbouteilleflacon",
			"image" : "pot_creme_fraiche_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_poterie",
			"type" : "Déchet",
			"nom" : "Poterie",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "poterie",
			"mots_cles" : "poterie",
			"cons" : "cons_verre",
			"image" : "pot_en_terre_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"commentaires" : "faq_pb_plastique",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_potPeinture",
			"type" : "Déchet",
			"nom" : "Pot peinture",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "pot de peinture, peinture à huile, peinture à l'eau, peinture, acrylique, peinture glycéro",
			"mots_cles" : "potpeinture, peinture a huile, peinture a leau, peinture, acrylique, peinture glycero",
			"cons" : "cons_toxique",
			"image" : "peinture_acrylique_mini.png",
			"image_secondaire" : "pot_peinture_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_potYaourt",
			"type" : "Déchet",
			"nom" : "Pot yaourt",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "pot de yaourt",
			"mots_cles" : "potyaourt",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "yaourt_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_produitPhytosanitaire",
			"type" : "Déchet",
			"nom" : "Produit phytosanitaire",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "produit phytosanitaire",
			"mots_cles" : "produit phytosanitaire",
			"cons" : "cons_toxique",
			"image" : "phytosanitaire_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_produitsBeaute",
			"type" : "Déchet",
			"nom" : "Produit beauté",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "produits de beauté, cosmétique, rouge à lèvres, maquillage, vernis",
			"mots_cles" : "produitsbeaute, cosmetique, rouge a levres, maquillage, vernis",
			"image" : "rouge_a_levre_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_produitsDEntretien",
			"type" : "Déchet",
			"nom" : "Produit d'entretien",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "produit d'entretien, nettoyant à sol",
			"mots_cles" : "produit dentretien, nettoyant a sol",
			"cons" : "cons_toxique",
			"image" : "produits_entretien_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_produitsTraitementDuBois",
			"type" : "Déchet",
			"nom" : "Produit traitement bois",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "produit de traitement du bois",
			"mots_cles" : "produittraitement du bois",
			"cons" : "cons_toxique",
			"image" : "traitement_de_bois_mini.png",
			"image_secondaire" : "teinte_a_bois_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_radiographie",
			"type" : "Déchet",
			"nom" : "Radiographie",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "radiographie",
			"mots_cles" : "radiographie",
			"cons" : "cons_toxique",
			"image" : "films_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_rasoirJetable",
			"type" : "Déchet",
			"nom" : "Rasoir jetable",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "rasoir jetable",
			"mots_cles" : "rasoir jetable",
			"image" : "rasoir_jetable_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_recurantsPourFour",
			"type" : "Déchet",
			"nom" : "Récurant pour four",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "récurant pour four",
			"mots_cles" : "recurant pour four",
			"cons" : "cons_toxique",
			"image" : "nettoyant_four_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_recurantsPourToilette",
			"type" : "Déchet",
			"nom" : "Récurant pour toilette",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "récurants pour toilette",
			"mots_cles" : "recurants pour toilette",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/produit_sanitaire_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_refrigerateur",
			"type" : "Déchet",
			"nom" : "Réfrigérateur",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "réfrigérateur",
			"mots_cles" : "refrigerateur",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "refrigerateur_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_resines",
			"type" : "Déchet",
			"nom" : "Résine",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "résine",
			"mots_cles" : "resine",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/resine_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_revelateurEtFixateurPhoto",
			"type" : "Déchet",
			"nom" : "Révélateur et fixateur photo",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "révélateur et fixateur photo",
			"mots_cles" : "revelateur et fixateur photo",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/fixateur_photo_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_sacEnPapier",
			"type" : "Déchet",
			"nom" : "Sac papier",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_papiercarton",
			"descr" : "sac en papier",
			"mots_cles" : "sac en papier",
			"cons" : "cons_souille,",
			"image" : "sac_papier_mini.png",
			"modco" : "modco_contpapiercarton,modco_bacjaune,modco_sacjaune,modco_contembjournmag",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_sacPlastique",
			"type" : "Déchet",
			"nom" : "Sac plastique",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "sac plastique",
			"mots_cles" : "sac plastique",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "sac_plastique_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_scooter",
			"type" : "Déchet",
			"nom" : "Scooter",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_encombrant",
			"descr" : "scooter, mobylette",
			"mots_cles" : "scooter, mobylette",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "scooter_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_solvants",
			"type" : "Déchet",
			"nom" : "Solvant",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "solvant, diluant, white spirit",
			"mots_cles" : "solvant, diluant, white spirit",
			"cons" : "cons_toxique",
			"image" : "bouteille_white_spirit_2_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_stylo",
			"type" : "Déchet",
			"nom" : "Stylo",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "stylo",
			"mots_cles" : "stylo",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "crayon_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_tableARepasser",
			"type" : "Déchet",
			"nom" : "Table à repasser",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_encombrant",
			"descr" : "table à repasser",
			"mots_cles" : "table a repasser",
			"cons" : "cons_numerosencombrants,cons_encombrants",
			"image" : "table_a_repasser_mini.png",
			"modco" : "modco_encombrant,modco_decheterie",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_telephonie",
			"type" : "Déchet",
			"nom" : "Téléphonie",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "téléphonie",
			"mots_cles" : "telephonie",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "telephone_fixe_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_televiseurs",
			"type" : "Déchet",
			"nom" : "Téléviseur",
			"cat_usuel" : "cu_encombrantelectronique",
			"cat_trait" : "cat_d3e",
			"descr" : "téléviseur",
			"mots_cles" : "televiseur",
			"cons" : "cons_recuppdv1,cons_ecoparticipation",
			"image" : "televiseur_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint,smco_reprise",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_thermometreAMercure",
			"type" : "Déchet",
			"nom" : "Thermomètre à mercure",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "thermomètre à mercure",
			"mots_cles" : "thermometre a mercure",
			"cons" : "cons_toxique",
			"image" : "thermometre_mercure_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_trompette",
			"type" : "Déchet",
			"nom" : "Trompette",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_instrument",
			"descr" : "trompette",
			"mots_cles" : "trompette",
			"image" : "images_non_libres_temp/trompette_mini.png",
			"modco" : "smco_reempdivers,modco_decheterie,modco_ecopoint,modco_encombrant",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_trottinnette",
			"type" : "Déchet",
			"nom" : "Trottinette",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_velo",
			"descr" : "trottinette",
			"mots_cles" : "trottinette",
			"image" : "trottinette_mini.png",
			"modco" : "smco_velo,modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 12/2014"
		}, {
			"code" : "dec_tubeFluorescent",
			"type" : "Déchet",
			"nom" : "Tube fluorescent",
			"cat_usuel" : "cu_toxique",
			"cat_trait" : "cat_ddm",
			"descr" : "tube fluorescent, tube fluo",
			"mots_cles" : "tube fluorescent, tube fluo",
			"cons" : "cons_toxique",
			"image" : "images_non_libres_temp/tube_flouorescent_mini.png",
			"modco" : "modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_tuyauDarrosage",
			"type" : "Déchet",
			"nom" : "Tuyau arrosage",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "tuyau d'arrosage",
			"mots_cles" : "tuyau darrosage",
			"cons" : "cons_pasuniquementbouteilleflacon",
			"image" : "tuyau_arrosage_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_UstensileCuisine",
			"type" : "Déchet",
			"nom" : "Ustensile cuisine",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_omr",
			"descr" : "ustensile de cuisine, casserole, marmite, cocotte, poêle, wok, spatule",
			"mots_cles" : "ustensilecuisine, casserole, marmite, cocotte, poele, wok, spatule",
			"image" : "spatule_cuisine_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_vaisselleCarton",
			"type" : "Déchet",
			"nom" : "Vaisselle carton",
			"cat_usuel" : "cu_papierscartons",
			"cat_trait" : "cat_omr",
			"descr" : "vaisselle carton, assiette carton, gobelet carton",
			"mots_cles" : "vaisselle carton, assiette carton, gobelet carton",
			"image" : "assiette_carton_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_vaissellePlastique",
			"type" : "Déchet",
			"nom" : "Vaisselle plastique",
			"cat_usuel" : "cu_plastique",
			"cat_trait" : "cat_omr_plastique",
			"descr" : "vaisselle plastique, gobelet plastique, couvert plastique, couteau plastique, fourchette plastique, cuillère plastique",
			"mots_cles" : "vaisselle plastique, gobelet plastique, couvert plastique, couteau plastique, fourchette plastique, cuillere plastique",
			"cons" : "cons_remplacergobelet,cons_vaissellebiodegradable,cons_pasuniquementbouteilleflacon",
			"image" : "gobelet_plastique_mini.png",
			"modco" : "modco_bacjaunenantes,modco_bacbleuhorsnantes,modco_sacbleu",
			"recyc" : "OUI_ET_NON",
			"src" : "MieuxTrierANantes 14/2014"
		}, {
			"code" : "dec_vaisselleVerrePorcelaine",
			"type" : "Déchet",
			"nom" : "Vaisselle (verre, porcelaine...)",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "assiette, tasse, bol, plat, verre à boire, poterie, porcelaine, faïence, carafe, verre",
			"mots_cles" : "assiette, tasse, bol, plat, verre a boire, poterie, porcelaine, faience, carafe, verre",
			"cons" : "cons_remplacergobelet,cons_vaissellebiodegradable,cons_verre",
			"image" : "assiette_mini.png",
			"image_secondaire" : "bol_mini.png, tasse_mini.png, plat_en_faience_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"commentaires" : "faq_pb_plastique",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_velo",
			"type" : "Déchet",
			"nom" : "Vélo",
			"cat_usuel" : "cu_metal",
			"cat_trait" : "cat_velo",
			"descr" : "vélo, bicyclette, vélo, skateboard",
			"mots_cles" : "velo, bicyclette, velo, skateboard",
			"image" : "veloenfant_mini.png",
			"image_secondaire" : "skateboard_mini.png",
			"modco" : "smco_velo,modco_decheterie,modco_ecopoint",
			"recyc" : "PAS_POUBELLE",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_vetementEnBonEtat",
			"type" : "Déchet",
			"nom" : "Vêtement bon état",
			"cat_usuel" : "cu_vetementtissu",
			"cat_trait" : "cat_vetement",
			"descr" : "vêtement en bon état, pantalon, chemise, pull, veste, jupe, robe",
			"mots_cles" : "vetement en bon etat, pantalon, chemise, pull, veste, jupe, robe",
			"image" : "chemise_mini.png",
			"modco" : "smco_conteneurlerelais,smco_reempvet,modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_vetementUsage",
			"type" : "Déchet",
			"nom" : "Vêtement usagé",
			"cat_usuel" : "cu_vetementtissu",
			"cat_trait" : "cat_omr",
			"descr" : "vêtement usagé, vêtement en mauvais état",
			"mots_cles" : "vetement usage, vetement en mauvais etat",
			"image" : "jean_usage_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_verreaboire",
			"type" : "Déchet",
			"nom" : "Verre à boire",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "verre à boire",
			"mots_cles" : "verre a boire",
			"cons" : "cons_verre",
			"image" : "verre_a_boire_petit.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"src" : "MieuxTrierANantes 12/2013"
		}, {
			"code" : "dec_vitre",
			"type" : "Déchet",
			"nom" : "Vitre",
			"cat_usuel" : "cu_verrevaisselle",
			"cat_trait" : "cat_verrenonvalovaisselleporcelaine",
			"descr" : "vitre",
			"mots_cles" : "vitre",
			"cons" : "cons_verre",
			"image" : "images_non_libres_temp/vitre_mini.png",
			"modco" : "modco_bacbleu,modco_sacbleu,modco_decheterie,modco_ecopoint,smco_vaisselle",
			"recyc" : "NON",
			"commentaires" : "faq_pb_plastique",
			"src" : "MieuxTrierANantes 02/2015"
		}, {
			"code" : "dec_voiture",
			"type" : "Déchet",
			"nom" : "Voiture",
			"cat_usuel" : "cu_divers",
			"cat_trait" : "cat_voiture",
			"descr" : "voiture",
			"mots_cles" : "voiture",
			"image" : "voiture_mini.png",
			"modco" : "smco_vendeurcassevoiture,modco_reprise",
			"recyc" : "OUI",
			"src" : "MieuxTrierANantes 02/2015"
		}, {}];
