var _infosDatas = [{
	"code" : "fiche_aremacs",
	"nom" : "Aremacs",
	"nom_en" : "Aremacs",
	"descr" : "<src img='resources/images/nantes/aremacs_mini.png' width='150px' /><br/>Aremacs est une association qui intervient lors des grands évènements pour le tri des déchets. <br/>Ils posent notamment des poubelles de tri pour les grands événements nantais, et veillent lors de toute la soirée à la bonne utilisation (et à vider) ces poubelles. <br/><br/>Son antenne sur Nantes est très active et de nombreux évènements sont couverts : le feu d'artifice, les rendez-vous de l'Erdre...<br/><br/>Adresse : 27 rue de Strasbourg, 44000 NANTES<br/>Tél : 02 51 82 37 23<br/>nantes@aremacs.com<br/><br/>Plus d'infos sur <a target=_blank href='http://www.aremacs.com/' >http://www.aremacs.com/</a>",
	"descr_en" : "<img src='resources/images/nantes/aremacs_mini.png' width='150px' /><BR/>Aremacs is an organization active at major events for sorting waste. They pose particular sorting bins for large events Nantes, and ensure during the whole evening to good use (and empty) these bins.<BR/>Nantes Its antenna is very active and many events are covered: the fireworks, the appointment of Erdre ...<BR/>Address: 27 rue de Strasbourg, 44000 NANTES<BR/>Tel: 02 51 82 37 23<BR/>nantes@aremacs.com<BR/>More information <a target='_blank' href='http://www.aremacs.com/ '> http://www.aremacs.com/ </a>",
	"bouton" : "fiche",
	"image" : "nantes/aremacs_mini.png",
	"mots_cles" : "aremacs,fete,evenement",
	"mots_cles_en" : "bins,yellow,blue"
}, {
	"code" : "fiche_bacjaune",
	"nom" : "Bacs jaunes et bleus",
	"nom_en" : "Yellow and blue bins",
	"descr" : "<IMG SRC='resources/images/bac_jaune_en_cours_mini.png' ALIGN='right' WIDTH='150px' /><LU>On peut mettre dans les bacs jaunes : <LI><B>le papier et le carton</B> : cartons (bruns), cartonnettes, emballage en carton, enveloppe, feuilles, journaux, magazines, prospectus,  boîte à œuf en carton, </LI> <LI><B>les briques alimentaires</B></LI> <LI><B>tous les types de plastique</B> : bouteille d'eau et de soda, bouteille d'huile (en plastique), tous les flacons, mais aussi <B>pots de yaourt, pots de crème fraîche, barquettes, films plastique</B></LI> <LI><B>les emballages en métal</B> : barquettes aluminium, canettes, boîtes de conserves, bombes aérosols</LI></UL><BR/><IMG SRC='resources/images/bac_bleu_mini.png' ALIGN='right' WIDTH='150px' />On met dans les bacs bleus les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "<IMG src='resources/images/bac_jaune_en_cours_mini.png' align='right' WIDTH='150px' /> <LU> You can put in the yellow bins: <LI> <B> paper and cardboard </b>: cartons (brown), cardboards, cardboard packaging, envelope, paper, newspapers, magazines, brochures, egg carton, </LI><LI> <B> Food brick </B> </LI><LI> <B> all types of plastics </B>: bottled water and soda, oil bottle (plastic), all bottles but <B> yogurt cups, cream jars , trays, plastic film </B> </LI><LI> <B> metal packaging </B>: aluminum trays, cans, tin cans, spray cans </LI></UL><BR/><IMG src='resources/images/bac_bleu_mini.png' align='right' WIDTH='150px' /> We put in the blue bins <B> non-recycled household waste </B>.",
	"bouton" : "fiche",
	"image" : "nantes/bacs_jaune_et_bleu.png",
	"mots_cles" : "bacs,jaunes,bleus",
	"mots_cles_en" : "caps,love"
}, {
	"code" : "fiche_bouchon_amour",
	"nom" : "Bouchons d'amour",
	"nom_en" : "Bouchons d'amour",
	"descr" : "<IMG SRC='resources/images/bouchon_plastique_mini.png' width='50px' /><b>Les bouchons suivant sont acceptés</b> : eau, lait, soda, huile, vinaigre, vin, compote, crème fraîche, liquide vaisselle, produits d'entretien, lessive, assouplissants, aérosols, déodorants, laque, parfum, dentifrice, shampooing,  produits douche, couvercle en plastique du chocolat, couvercle en plastique du café en poudre, couvercle en plastique de la moutarde.<br/><br/><b>Bouchons refusés</b> : produits toxiques, détergents.<br/><br/>Plus d'infos : <a href='http://www.bouchonsdamour.com/les-bons-bouchons' target='_blank' id='bouchons_amour_link'>http://www.bouchonsdamour.com/les-bons-bouchons</a>",
	"descr_en" : "<IMG src='resources/images/bouchon_plastique_mini.png' width='50px' /> <b> The following plugs are accepted </b>: water, milk, soda, oil, vinegar, wine, sauce, cream, dishwashing liquid, cleaning products, laundry softeners, aerosols, deodorants, hairspray, perfume, toothpaste, shampoo, shower products, plastic cover chocolate, powdered coffee plastic cover, plastic cover mustard.<BR/><BR/><b> Stoppers denied </b>: toxic products, detergents<BR/>More. <a href='http: //www.bouchonsdamour.com/les -bons-caps' target = '_ blank' id = 'bouchons_amour_link'> http://www.bouchonsdamour.com/les-bons-bouchons </a>",
	"bouton" : "fiche",
	"image" : "bouchon_plastique_mini.png",
	"mots_cles" : "bouchons,amour",
	"mots_cles_en" : "collection,bulky"
}, {
	"code" : "fiche_encombrant",
	"nom" : "Collecte des encombrants",
	"nom_en" : "Collection of bulky",
	"descr" : "<img src='resources/images/nantes/encombrant.jpg' align='right' /><br/>Pour les logements verticaux (appartement...) les encombrants sont récupérés à jour fixe dans la semaine (affiché en général en bas de l'immeuble).<br/>Pour les logements pavillonnaires (maisons...) le ramassage se fait sur rendez-vous à prendre par téléphone (numéros ci-dessous).",
	"descr_en" : "<img src='resources/images/nantes/encombrant.jpg' align='right' /><BR/>For vertical housing (apartment ...) are recovered bulky fixed day in the week (usually displayed at the bottom of the building). In order to the suburban housing (houses ...) collection is by appointment to be made by telephone (numbers below).",
	"bouton" : "fiche",
	"image" : "nantes/encombrant_mini.png",
	"mots_cles" : "collecte,encombrant",
	"mots_cles_en" : "collection,bulky"
}, {
	"code" : "fiche_compostage",
	"nom" : "Compostage",
	"nom_en" : "Composting",
	"descr" : "<IMG SRC='resources/images/composteur_mini.png' ALIGN='left' />Le compostage est un processus de décomposition. En première phase, la température peut atteindre jusqu'à 70°, et une bonne aération est nécessaire (pour les bactéries 'aérobies'). En seconde phase, champignons, lombrics et autres petits animaux sont à l'œuvre Il faut 6 mois-1 an pour un bon compost.<BR/><BR/><B>Le compost peut contenir</B> :<BR/> - les restes de la cuisine : céréales, épluchures, fruits, légumes, marc de café, sachets de thé,<BR/> - les restes du jardin : fleurs fanées, feuilles mortes, foin, gazon séché, mauvaises herbes, paille, plantes de jardin, sciure de bois en petite quantité,<BR/> - les restes de la maison : cendres (en petite quantité), cheveux, essuie-tout, filtres à café, mouchoirs en papier, papier, poussière.<BR/><BR/><IMG SRC='resources/images/epeluchure_mini.png' ALIGN='right' /><B>De préférence, éviter</B> :<BR/> - le pain en grosse quantité,<BR/> - les coquilles d'œufs (non biodégradable),<BR/> - les écorces d'agrumes non traités.<BR/><BR/><B>Ne surtout pas mettre</B><BR/> :  - branches en grosse quantité,<BR/> - coquilles de noix et noisettes,<BR/> - écorces d'agrumes traités,<BR/> - feuilles de noyer ou rhubarbe,<BR/> - fromage (attire rats, souris...),<BR/> - graisses,<BR/> - herbes traitées,<BR/> - laits et produits laitiers,<BR/> - litières animaux,<BR/> - plantes malades, <BR/> - reste de taille de jardinage en grosse quantité,<BR/> - viandes (odeur forte, attire rats, chiens...).<BR/><BR/><B>Quelques conseils</B> :<BR/> - équilibrer entre déchets secs et humides,<BR/> - aérer : ne pas tasser, mais retourner de temps en temps,<BR/> - mouiller un peu.<BR/><BR/><FONT COLOR=red>Source principale : <A HREF='http://fr.ekopedia.org/Compost' TARGET='_new'>article Compost sur Ékopédia</A></FONT>",
	"descr_en" : "<IMG src='resources/images/composteur_mini.png' align='left' /> Composting is the decomposition process. In first phase, the temperature can reach up to 70 °, and good ventilation is required (for the bacteria 'aerobic'). In second phase, fungi, earthworms and other small animals are at work It takes 6 months-1 year for good compost<BR/><BR/><B> Compost can contain </B>. <BR /> - the kitchen scraps cereals, vegetable peelings, fruit, vegetables, coffee grounds, tea bags,<BR/>- the remains of the garden: faded flowers, leaves, hay, dried grass, weeds, straw , garden plants, sawdust sparingly,<BR/>- the remains of the house: ash (in small quantities), hair, paper towels, coffee filters, paper towels, paper, dust<BR/><BR/><IMG src='resources/images/epeluchure_mini.png' align='right' /> <B> Preferably avoid </B>:<BR/>- the bread in large quantities, < BR /> - egg shells (non-biodegradable)<BR/>. - untreated citrus peel<BR/><BR/><B> Please do not put </B><BR/>- branches in large quantities,<BR/>- hazelnut and walnut shells,<BR/>- treated citrus peel,<BR/>- walnut leaves or rhubarb,<BR/>- cheese (attracts rats, mouse ...),<BR/>- fats,<BR/>- processed herbs,<BR/>- milk and dairy products,<BR/>- pet beds,<BR/>- diseased plants,<BR/>- rest of gardening in bulk size,<BR/>- meats (strong smell attracts rats, dogs ...)<BR/><BR/><B> Tips </B>:<BR/>- balance between dry and wet waste<BR/>- airing: do not pack, but return occasionally,<BR/>- a little wet<BR/><BR/><FONT COLOR=red> Main source: <A HREF='http://fr.ekopedia.org/Compost' TARGET='_new'> Article Compost on Ekopedia </A> </font>",
	"bouton" : "fiche",
	"image" : "composteur_mini.png",
	"mots_cles" : "compostage",
	"mots_cles_en" : "compostri"
}, {
	"code" : "fiche_compostri",
	"nom" : "Compostri",
	"nom_en" : "Compostri",
	"descr" : "<img src='resources/images/nantes/logo_compostri_mini.png' width='250px' /><br/><br/>C'est une association nantais qui aide à la constructions de composteurs collectifs, en accompagnant les particuliers à la création et l'alimentation du composteur.<b>Compostri favorise la mise en place de projets de compostage partagé</b> et accompagne les habitants dans cette démarche à l'échelle d'un quartier, immeuble, groupe d'immeubles, écoles maternelles et primaires ... <b>sur le territoire de Nantes Métropole</b> et avec le soutien de cette collectivité.<br/><br/>Aujourd'hui 120 sites de compostage partagé sont en fonctionnement sur le territoire nantais. Ces pavillons sont mis en place grâce au soutien de Nantes Métropole.<br/>Compostri et ses 3 guides composteurs accompagnent les citoyens porteurs de projets : aide à l'installation de pavillons de compostage, formation, suivi technique.<br/><br/>Cette association accompagne également les groupes scolaires: restaurants associatifs, foyers de jeunes, EHPAD et dernièrement une moyenne surface (30 tonnes de bio-déchets /an).<br/><br/>Adresse : 18, quai du Président Wilson, 44200 Nantes<br/><br/>Tél : 09 82 45 22 21<br/><br/>courriel : contact@compostri.fr<br/><br/><a href='http://www.compostri.fr/' target=_blank>http://www.compostri.fr/</a>",
	"descr_en" : "<img src='resources/images/nantes/logo_compostri_mini.png' width='250px' /><BR/>Nantes This is a combination that helps the construction of collective composters, accompanying individuals to the creation and supply of compost. <b> Compostri promotes the establishment of shared composting projects </b> and accompanies the people in this process at the neighborhood level, building, group of buildings, kindergartens and schools ... <b> in the territory of Nantes Métropole </b> and with the support of this community. Today<BR/>120 shared composting sites are operating on the territory Nantes. These pavilions are set up with the support of Nantes Métropole<BR/>Compostri and three composters guides accompany project promoters citizens. Installation help composting pavilions, training, technical monitoring<BR/><. br /> This association also accompanied school groups. associative restaurants, hostels for young, retirement homes and lately an average size (30 tonnes of bio-waste / year)<BR/>Address: 18, President of the dock Wilson, 44200 Nantes<BR/>Tel: 09 82 45 22 21<BR/>email: contact@compostri.fr<BR/><a href='http://www.compostri.fr/ 'target='_blank'> http://www.compostri.fr/ </a>",
	"bouton" : "fiche",
	"image" : "nantes/logo_compostri_mini.png",
	"mots_cles" : "compostri",
	"mots_cles_en" : "container,packaging,newspaper,magazine"
}, {
	"code" : "fiche_contembjournmag",
	"nom" : "Cont. embal. journ. mag.",
	"nom_en" : "Cont. embal. journ. Mag.",
	"descr" : "<IMG SRC='resources/images/conteneur_emballages_journaux_magazines_instructions.jpg' width='250px' /> <IMG SRC='resources/images/conteneur_emballages_journaux_magazines_instructions2.jpg' width='250px' /><BR/>On peut mettre dans le conteneur emballages journaux magazines : boîte de conserve, barquette aluminium, cannette, aérosol, bouteille métal sirop, bouteilles d'eau, flacon, brique (jus de fruit, lait), cartonnettes, papier, journaux, magazines",
	"descr_en" : "<IMG src='resources/images/conteneur_emballages_journaux_magazines_instructions.jpg' width='250px' /> <IMG SRC='resources/images/conteneur_emballages_journaux_magazines_instructions2.jpg' width='250px' /><BR/>can be put in the container magazines newspapers packaging: tin, aluminum trays, cans, aerosol metal syrup bottle, water bottles, bottle, brick (fruit, milk juice), cardboards, paper, newspapers, magazines",
	"bouton" : "fiche",
	"image" : "conteneur_emballages_journaux_magazines_mini.png",
	"mots_cles" : "conteneur,emballage,journal,magasine",
	"mots_cles_en" : "containers,clothing"
}, {
	"code" : "fiche_contvet",
	"nom" : "Conteneurs vêtements",
	"nom_en" : "Containers clothing",
	"descr" : "<IMG SRC='resources/images/conteneur_le_relais_instructions.jpg' WIDTH='250px' /><br/><b>Des sociétés récupèrent les vêtements pour les revendre</b>. En 2013 une dizaine de société (aucune association) possèdent 28 000 conteneurs en France et récupèrent environ 200 000 tonnes de vêtements. <i>D'un côté la tonne de textile usagé est passée de 80 € la tonne en 2007 à 400 € en 2013. De l'autre l'éco-contribution textile, mise en place en 2008 (perçu 0,005 € pour chaque vêtement vendu) est reversée vers les sociétés européennes qui traite le textile recyclé (56 euros la tonne) soit au global 13 millions d'euros)</i>.<br/><br/><b>Ce système a des défauts.</b> L'éco-contribution textile est reversée sans que des contrôles sérieux n'ait lieu (<b>le tri n'est pas toujours réalisé</b>) et cela produit <b>beaucoup de transport</b>. Les vêtements ne sont <b>pas redistribués aux personnes dans le besoin mais revendus</b> (les autocollants des associations sur les conteneurs - comme 'Emmaüs' - signifie que la société qui gère le conteneur reverse de l'argent à une association).<br/><br/><b>Le Relais</b> est une SCOP (société coopérative ouvrière de production), créés en 1984, numéro un (55 %) de la collecte en France. L'objectif était de ramener vers l'emploi des personnes que Emmaüs avait accueillies. Elle fait donc de la réinsertion sociale (actuellement 2500 employés dans le monde, dont 2000 en France) avec un chiffre d'Affaire en 2013 de 180 millions euros. Elle a 19000 conteneurs, 600 camions et traite 100 000 tonnes de vêtements usagés.<br/>Le vêtements ne sont pas redistribués : les vêtements de marque sont revendus dans les boutiques Le Relais, les autres sont exportés (notamment vers l'Afrique où la plupart est revendue, certains se retrouvent dans des dépotoirs) et ceux qui sont usagés (30 %) sont transformés en isolant et revendus pour l'industrie.",
	"descr_en" : "<IMG src='resources/images/conteneur_le_relais_instructions.jpg' WIDTH='250px' /><BR/><b> Companies retrieve clothes for resale </b>. In 2013 ten Company (no association) have 28,000 containers in France and recover about 200 000 tonnes of clothes. <i> On one side tonne of used textiles rose from € 80 per tonne in 2007 to € 400 in 2013. On the other textile eco-contribution, established in 2008 (received € 0.005 for each garment sold) is paid to European companies that processes the recycled textiles (56 per tonne) at € 13 million overall) </ i>.<BR/><b> This system has flaws. </b> The textile eco-contribution is paid without serious control takes place (<b> sorting is not always realized </b>) and this produces <b> many transportation </b>. Clothes are <b> not distributed to those in need but resold </b> (stickers on the containers associations - such as Emmaus' - means that the company that manages the container pays money to an association ).<BR/><b> Le Relais </b> is a SCOP (workers' production cooperative), created in 1984, a number (55%) of the collection in France. The goal was to bring people into employment that Emmaus had welcomed. It therefore made social reintegration (currently 2,500 employees worldwide, including 2,000 in France) with annual Business in 2013 of 180 million euros. She containers 19000, 600 trucks and treats 100,000 tons of used clothing<BR/>The clothes are not redistributed. Designer clothes are sold in boutiques Le Relais, others are exported (especially to Africa where most is sold, some end up in dumps) and those used (30%) were processed by isolating and sold to the industry.",
	"bouton" : "fiche",
	"image" : "conteneur_lerelais_mini.png",
	"mots_cles" : "conteneurs,vetements",
	"mots_cles_en" : ""
}, {
	"code" : "fiche_coucheslavables",
	"nom" : "Couches lavables",
	"nom_en" : "Cloth diapers",
	"descr" : "Pourquoi ne pas tester les couches lavables ? Une couche de bonne qualité coûte entre 15 et 20 euros, et se revend 7 euros d'occasion. Il en faut environ 25 (il est recommandé de changer le bébé 8-9 fois par jour pour ce type de couche). Certaines couches sont moins épaisses, et ne donnent pas cet effet 'gros popotin'. Voir 'vente en vrac' sur la page Lieux.<br/><br/><img src='resources/images/nantes/logo_arbalange.png' /><br/><b>Arbalange</B><br/>En 2009, des Nantais ont créés Arbalange. Cette SARL alimentait des crèches en couches lavables. Elle s'est diversifiée (confection/vente de couches), mais a fermé en 2011. Retour sur cette expérience.<br/><a href='http://www.atelier-idf.org/ressources/breves/2012-01-27,arbalange-explications-faillite.htm' target='_blank'>Article 'Arbalange : pourquoi ça a fermé'</a>",
	"descr_en" : "Why not test cloth diapers? A layer of good quality costs between 15 and 20 euros, and resells used 7 euros. It takes about 25 (it is recommended to change the baby 8-9 times per day for this type of layer). Some layers are thinner, and do not give this effect 'big butt'. See 'loose sales' on the page 'Lieux'.<BR/><img src='resources/images/nantes/logo_arbalange.png'/><br/><b>Arbalange</B><br/>In 2009, they created Arbalange Nantais. This fueled SARL nurseries in cloth diapers. . It expanded (manufacture / sale of layers), but closed in 2011. Back on this experience<BR/><a href='http://www.atelier-idf.org/ressources/breves/2012-01to27,arbalange-explanations-faillite.htm' target='_ blank'>Article 'Arbalange : why it closed'</a>",
	"bouton" : "fiche",
	"image" : "couches_lavables_1.png",
	"mots_cles" : "couche,lavable,arbalange",
	"mots_cles_en" : "cloth,diaper,arbalange"
}, {
	"code" : "fiche_contpapiercarton",
	"nom" : "Conteneur papier carton",
	"nom_en" : "Paper cardboard container",
	"descr" : "<IMG SRC='resources/images/conteneur_carton_instructions.jpg' width='250px' /> <IMG SRC='resources/images/conteneur_carton_instructions_2.jpg' width='250px' /><BR/>On peut mettre dans le conteneur papier et carton : cartons (bruns), cartonnettes, emballage en carton, enveloppe, feuilles, journaux, magazines, prospectus,  boîte à œuf en carton.",
	"descr_en" : "<IMG src='resources/images/conteneur_carton_instructions.jpg' width='250px' /> <IMG SRC='resources/images/conteneur_carton_instructions_2.jpg' width='250px' /><BR/>can be put in the container paper and cardboard: boxes (brown), cardboards, cardboard packaging, envelope, paper, newspapers, magazines, brochures, egg carton.",
	"bouton" : "fiche",
	"image" : "conteneur_carton_mini.png",
	"mots_cles" : "conteneur,papier,carton",
	"mots_cles_en" : "container,paper,cardboard"
}, {
	"code" : "fiche_contmpb",
	"nom" : "Conteneur plastique",
	"nom_en" : "Plastic container",
	"descr" : "<IMG SRC='resources/images/conteneur_plastique_instructions.jpg' width='250px' /><IMG SRC='resources/images/conteneur_plastique_instructions_2.jpg' width='250px' /><BR/>On peut mettre dans le conteneur plastique tous les bouteilles transparentes (eau, soda), les bouteilles de lait, bouteille d'huile (en plastique), les flacons (lessive, javel, nettoyant ménager...) sauf ceux ayant contenus des produits toxiques (ayant une croix rouge) ou inflammables (flamme rouge). On ne doit pas mettre les barquettes en polystyrène, les pots de yaourts, les sacs plastiques de supermarchén.",
	"descr_en" : "<IMG src='resources/images/conteneur_plastique_instructions.jpg' width='250px' /> <IMG SRC='resources/images/conteneur_plastique_instructions_2.jpg' width='250px' /><BR/>can be put in the container all plastic transparent bottles (water, soda), milk bottles, bottle of oil (plastic) bottles (detergent, bleach, household cleaners ...) except those that contained toxic products (with a red cross ) or flammable (flame red). We should not put the Styrofoam trays, yoghurt pots, plastic bags supermarchén.",
	"bouton" : "fiche",
	"image" : "conteneur_plastique_mini.png",
	"mots_cles" : "conteneur,plastique",
	"mots_cles_en" : "container,plastic"
}, {
	"code" : "fiche_contverre",
	"nom" : "Conteneur verre",
	"nom_en" : "Glass container",
	"descr" : "<IMG SRC='resources/images/conteneur_verre_instructions_2.jpg' WIDTH='200px' /> <IMG SRC='resources/images/conteneur_verre_instructions.jpg' WIDTH='200px' /><BR/>On peut mettre dans le conteneur verre tour le verre ménager : bouteilles, pots, bocaux. En revanche il ne faut pas mettre la vaisselle, les pôts, les ampoules.",
	"descr_en" : "<IMG src='resources/images/conteneur_verre_instructions_2.jpg' WIDTH='200px' /> <IMG SRC='resources/images/conteneur_verre_instructions.jpg' width='200px' /><BR/>can put in the container glass tower housework glass: bottles, pots, jars. However we must not put the dishes, pots, bulbs.",
	"bouton" : "fiche",
	"image" : "conteneur_verre_mini.png",
	"mots_cles" : "conteneur,verre",
	"mots_cles_en" : "container,glass"
}, {
	"code" : "fiche_ecopoint",
	"nom" : "Déchèteries / écopoint",
	"nom_en" : "Déchèteries / écopoint",
	"descr" : "<IMG SRC='resources/images/nantes/ecopoint_panneau_labeaujoire.jpg' WIDTH='300px' ALIGN='right' /><IMG SRC='resources/images/nantes/ecopoint_viarme_mini.png' WIDTH='200px' /><BR/>Les déchèteries et les écopoints sont <B>réservés aux particuliers habitant la Communauté Urbaine de Nantes</B>.<BR/>Les Ecopoints sont des mini-déchetteries où seuls les gravats ne sont pas admis. Il y en a 4 sur Nantes.<BR/><UL>Les déchets suivants sont admis :<LI>déblais, gravats, encombrants</LI><LI>les appareils électriques</LI><LI>les déchets toxiques (en petites quantités dans les écopoints) : peinture, vernis, colle, diluants, batteries, huiles moteur...</LI><LI>les déchets verts</LI><LI>les bouteilles et les flacons plastiques</LI><LI>papiers, cartons, cartonnettes</LI><LI>le verre (uniquement le verre ménager) : pôts, bouteilles</LI><LI>le métal</LI></UL>",
	"descr_en" : "<IMG src='resources/images/nantes/ecopoint_panneau_labeaujoire.jpg' WIDTH='300px' align='right' /> <IMG SRC='resources/images/nantes/ecopoint_viarme_mini.png' width='200px' /><BR/>déchèteries and ecopoints are <B> reserved for individuals living in the Nantes Urban Community </B>.<BR/>Ecopoints are mini recycling centers where only rubble are not allowed. There are 4 on Nantes<BR/><UL> The following shall be permitted:. <LI> rubble, rubble, bulky </LI><LI> electrical appliances </LI><LI> toxic waste ( in small amounts in ecopoints): paint, varnish, glue, thinners, batteries, motor oil ... </LI><LI> green waste </LI><LI> bottles and plastic bottles </LI><LI> paper, cardboard, cardboards </LI><LI> glass (only the domestic glass): Pots, bottles </LI><LI> metal </LI></ UL>",
	"bouton" : "fiche",
	"image" : "nantes/ecopoint_viarme_mini.png",
	"mots_cles" : "decheteries,ecopoint",
	"mots_cles_en" : "decheteries,ecopoint"
}, {
	"code" : "fiche_ecoparticipation",
	"nom" : "Eco-participation",
	"nom_en" : "Green tax",
	"descr" : "<IMG SRC='resources/images/ticket_caisse_ecoparticipation_mini.png' ALIGN='right' />A l'achat d'un appareil neuf, vous payez une 'éco-participation', qui correspond au coût de collecte, de réemploi, de dépollution et de recyclage d'un appareil usagé équivalent. Son montant varie selon le produit et le type de traitement qu'il nécessite.<BR/><BR/>L'éco-participation est indiquée sur les étiquettes de manière visible et séparée du prix du produit. C'est un outil de transparence et d'information. Elle est intégralement versée à un éco-organisme comme Eco-systèmes agréé par les pouvoirs publics pour prendre en charge les anciens appareils.",
	"descr_en" : "<IMG src='resources/images/ticket_caisse_ecoparticipation_mini.png' align='right' /> When buying a new appliance, you pay an eco-contribution', which is the cost of collection, reuse, decontamination and recycling an old appliance equivalent. The amount varies depending on the product and type of treatment he requires.<BR/><BR/>Eco-share is stated on labels and visibly separated from the product price. It is a tool of transparency and information. It is fully paid to an environmental organization Eco-systems as approved by the government to support older devices.",
	"bouton" : "fiche",
	"image" : "ticket_caisse_ecoparticipation_mini.png",
	"mots_cles" : "eco,participation,taxe",
	"mots_cles_en" : "greentax"
}, {
	"code" : "fiche_poubelle",
	"nom" : "Eugène Poubelle",
	"nom_en" : "Eugène Poubelle",
	"descr" : "<IMG SRC='resources/images/images_externes_libres/portrait_eugene_poubelle.jpg' ALIGN='right' /><ul>En 1883, pour lutter contre la saleté des rues de Paris, le préfet Eugène Poubelle signe un arrêté :<li>les propriétaires doivent fournir un récipient (commun à tous les locataires) pour les déchets ménagers</li><li>3 boîtes de tri sont obligatoires par locataire : matières putrescibles, papiers/chiffons, verre/faïence/coquilles d'huîtres</li><li>le ramassage régulier de ces réceptacles est organisé.</li></ul>L'hostilité des propriétaires (coût), des concierges (surcroît de travail), des chiffonniers (perte du gagne-pain) fit que peu-à-peu les anciennes boîtes ne furent pas remplacées, et au bout du compte on arrêta le tri des déchets.<br/><br/><b>Monsieur Poubelle laissa son nom au récipient, mais il faut reconnaître en lui un des précurseur du tri</b> même s'il ne fut pas suivi à cause de certains corporatismes.<br/><P class='source'>Source principale : <A HREF='http://fr.wikipedia.org/wiki/Eug%C3%A8ne_Poubelle' TARGET='_blank'>article sur Wikipédia (l'image provient de ce site)</A>",
	"descr_en" : "<IMG src='resources/images/images_externes_libres / portrait_eugene_poubelle.jpg' align='right' /> <ul> In 1883, the fight against dirt streets of Paris, the prefect Eugène Trash sign an order: <li> Owners must provide a container (common to all tenants) for household waste </ li> <li> 3 sorting boxes are required by tenant putrescible waste, paper / rags, glass / china / oyster shells </ li > <li> the regular collection of these containers is organized. </ li> </ ul> The hostility owners (cost), janitors (extra work), ragpickers (loss of livelihoods) made little -to little old boxes were not replaced, and in the end we stopped sorting waste.<BR/><b> Mr. Bin gave his name to the container, but we must recognize in him a precursor sorting </b> even if it was not followed because of certain corporatism<BR/><P class='source'> Main. Source: <a href='http: //fr.wikipedia. org / wiki /% C3% Eug A8ne_Poubelle TARGET = '_ blank'> article on Wikipedia (the image from this site) </A>",
	"bouton" : "fiche",
	"image" : "images_externes_libres/portrait_eugene_poubelle_mini.png",
	"mots_cles" : "eugene,poubelle",
	"mots_cles_en" : "eugene,poubelle"
}, {
	"code" : "fiche_logos",
	"nom" : "Logos utilisés",
	"nom_en" : "Logos used",
	"descr" : "<IMG SRC='resources/images/images_non_libres/logo_contribution_petit.png' width='50px' /> Le fabriquant verse une contribution à l'une de ces trois sociétés : Eco-Emballage, Adelphe ou Cyclamed. <B>Ceci ne signifie pas que le produit est recyclable</B>.<BR/><IMG SRC='resources/images/images_non_libres/logo_triman.png' width='50px' />Il existe une consigne de tri.</B>.<BR/><IMG SRC='resources/images/images_non_libres/moebius_sans_mini.png' width='50px' /> Ce produit ou cet emballage est <B>recyclable</B>.<BR/><IMG SRC='resources/images/images_non_libres/moebius_mini.png' width='50px' /> Ce produit ou cet emballage contient <B>65 % de matières recyclées</B>.<BR/><BR/><IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pete_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-hdpe_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pvc_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-ldpe_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pp_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-ps_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-autres_mini.png' width='50px' /><BR/>Les logos sur les plastiques (listes des produits non exhaustives) : <LI>1 : PET (Polyéthylène Teraphtalate) : bouteilles de soda <B>recyclable</B></LI><LI>2 : PEHD (Polyéthylène haute densité) : bouteille de lait, jus de fruit, javel, détergent, de shampoing, <B>recyclable</B></LI><LI>3 : PVC (PolyChlorure de Vinyle) : bouteilles détergent, shampoing, tuyau gris, gaine électrique... <B>recyclable</B> (rarement recyclé)</LI><LI>4 : PELD (Polyéthylène basse densité) : bouteilles compressibles, sacs cabas, moquettes : <B>pas recyclable</B> (ou difficilement)</LI><LI>5 : PP (Polypropylène) : pots de yaourt, bouteilles de ketchup, bouchons de boisson gazeuses... <B>pas recyclable</B> (ou difficilement, comme Les Bouchons d'Amour)</LI><LI>6 : PSE (Polystyrène Expansé) : assiettes jetables, boitiers CDs, barquette alimentaire <B>pas recyclable</B> (ou difficilement)</LI><LI>7 : autres plastiques <B>pas recyclable</B> (ou difficilement)</LI><B>Privilégiez les produits avec les logos 1 et 2</B>.<BR/>Plus d'infos : <A HREF='http://www.lemballageecologique.com/actualites/symboles-logos-recyclage-emballages-plastiques/' target='_blank'>http://www.lemballageecologique.com/actualites/symboles-logos-recyclage-emballages-plastiques/</A>",
	"descr_en" : "<IMG src='resources/images/images_non_libres/logo_contribution_petit.png' width='50px' /> The manufacturer is contributing to one of these three companies: Eco-Emballage, Adelphe or Cyclamed. <B> This does not mean that the product is recyclable </B>.<BR/><IMG SRC='resources/images/images_non_libres/logo_triman.png' width='50px' />There is a sorting instruction.</B>.<BR/><IMG src='resources/images/images_non_libres/moebius_sans_mini.png' width='50px' /> This product or the packaging is <b>recycled </B>.<BR/><IMG src='resources/images/images_non_libres/moebius_mini.png' width='50px' /> This product and the packaging contains <B> 65% recycled materials </B>.<BR/><BR/><IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pete_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-hdpe_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pvc_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-ldpe_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pp_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-ps_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-autres_mini.png' width='50px' /><BR/>logos on plastic (non-exhaustive list of products): <LI> 1: PET (Polyethylene terephthalate) bottles of soda <B> recycled </B> </LI><LI> 2: HDPE (high density polyethylene) bottle of milk, fruit, bleach juice, detergent, shampoo, <B> recycled </B> </LI><LI> 3: PVC (polyvinyl chloride) : detergent bottles, shampoo, gray pipe, electrical conduit ... <B> recycled </B> (rarely recycled) </LI><LI> 4: LDPE (Low Density Polyethylene): squeeze bottles, shopping bags, carpet: <B> not recyclable </B> (or difficult) </LI><LI> 5: PP (Polypropylene): yogurt cups, ketchup bottles, soft drink caps ... <B> not recyclable </b> (or difficult, as the plugs Love) </LI><LI> 6: EPS (Expanded Polystyrene): disposable plates, housings CDs, food tray <B> not recyclable </B> (or difficult) </LI><LI> 7: other plastics <B> not recyclable </B> (or difficult) </LI><B> Favour products with the logos 1 and 2 </B><BR/>More. Info: <A HREF='http://www.lemballageecologique.com/actualites/symboles-logos-recyclage-emballages-plastiques/' target='_blank'>http://www.lemballageecologique.com/actualites/symboles-logos-recyclage-emballages-plastiques/</A>",
	"bouton" : "fiche",
	"image" : "images_non_libres/logo_contribution_mini.png",
	"mots_cles" : "logo,eco,emballage,adelphe,cyclamed,pet,pehd,peld,pp,pse,triman",
	"mots_cles_en" : "logo,eco,emballage,adelphe,cyclamed,pet,pehd,peld,pp,pse,triman"
}, {
	"code" : "fiche_lombricompost",
	"nom" : "Lombricompost",
	"nom_en" : "Vermicompost",
	"descr" : "<IMG SRC='resources/images/images_non_libres/logo_contribution_petit.png' width='50px' /> Le fabriquant verse une contribution à l'une de ces trois sociétés : Eco-Emballage, Adelphe ou Cyclamed. <B>Ceci ne signifie pas que le produit est recyclable</B>.<BR/><IMG SRC='resources/images/images_non_libres/logo_triman.png' width='50px' />Il existe une consigne de tri.</B>.<BR/><IMG SRC='resources/images/images_non_libres/moebius_sans_mini.png' width='50px' /> Ce produit ou cet emballage est <B>recyclable</B>.<BR/><IMG SRC='resources/images/images_non_libres/moebius_mini.png' width='50px' /> Ce produit ou cet emballage contient <B>65 % de matières recyclées</B>.<BR/><BR/><IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pete_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-hdpe_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pvc_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-ldpe_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-pp_mini.png' width='50px' />  <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-ps_mini.png' width='50px' /> <IMG SRC='resources/images/images_non_libres/logo-emballage-plastique-autres_mini.png' width='50px' /><BR/>Les logos sur les plastiques (listes des produits non exhaustives) : <LI>1 : PET (Polyéthylène Teraphtalate) : bouteilles de soda <B>recyclable</B></LI><LI>2 : PEHD (Polyéthylène haute densité) : bouteille de lait, jus de fruit, javel, détergent, de shampoing, <B>recyclable</B></LI><LI>3 : PVC (PolyChlorure de Vinyle) : bouteilles détergent, shampoing, tuyau gris, gaine électrique... <B>recyclable</B> (rarement recyclé)</LI><LI>4 : PELD (Polyéthylène basse densité) : bouteilles compressibles, sacs cabas, moquettes : <B>pas recyclable</B> (ou difficilement)</LI><LI>5 : PP (Polypropylène) : pots de yaourt, bouteilles de ketchup, bouchons de boisson gazeuses... <B>pas recyclable</B> (ou difficilement, comme Les Bouchons d'Amour)</LI><LI>6 : PSE (Polystyrène Expansé) : assiettes jetables, boitiers CDs, barquette alimentaire <B>pas recyclable</B> (ou difficilement)</LI><LI>7 : autres plastiques <B>pas recyclable</B> (ou difficilement)</LI><B>Privilégiez les produits avec les logos 1 et 2</B>.<BR/>Plus d'infos : <A HREF='http://www.lemballageecologique.com/actualites/symboles-logos-recyclage-emballages-plastiques/' target='_blank'>http://www.lemballageecologique.com/actualites/symboles-logos-recyclage-emballages-plastiques/</A> ",
	"descr_en" : "The lombricopost (or vermicompost) can convert biodegradable waste into natural fertilizer. Are used to rapidly degrade waste<BR/><BR/><B> No fermentation, so almost no odor </b><BR/>Unlike conventional compost there is no fermentation. There remains a slight smell of humus.<BR/><BR/><B> The compost worms </B><BR/>These worms (one of 150 earthworm species) can eat between half and 2 times their weight per day. They reproduce rapidly (the population can double every three months). They are sold on the Internet, in fishing the supermarket shelf. They can be found also in the pile of manure. They live in an environment between 15 and 25 degrees<BR/><BR/><B> The composter </B><BR/>The most common model is called horizontal. It includes 2 adjacent bins allowing rotation ( when the first is full, it then uses the second). If composters can be easily manufactured, you can buy them: be between 35 and 180 euros vermicomposter<BR/><BR/><B> A place </B><BR/>Rest of fruits and vegetables, paper. , cardboard, egg shells, nuts / nut shells, tree leaves, coffee grounds, tea bags, vacuum cleaner dust<BR/><BR/><B> Avoid </B> <BR /> citrus, leeks, onions, shallots, pasta, rice, bread, hair, nails.<BR/><BR/><B> Do not </B><BR/>rhubarb, garlic, used tissues, meat , fish, litter, animal manure, dairy, fat and oil.<BR/><BR/><B> Warning moisture </B><BR/>To avoid the presence of flies, we must reduce the moisture compost, putting paper, cardboard, newspaper, coffee grounds ...<BR/><BR/>Main source: <A HREF = 'http: //fr.ekopedia.org/Lombricompostage' target = ' _blank '> http://fr.ekopedia.org/Lombricompostage </A>.<BR/>",
	"bouton" : "fiche",
	"image" : "compost_mini.png",
	"mots_cles" : "lombricompost",
	"mots_cles_en" : "vermicompost"
}, {
	"code" : "fiche_mieuxtrierannantes",
	"nom" : "Mieux trier à Nantes",
	"nom_en" : "Mieux trier à Nantes",
	"descr" : "Application et site Internet 'Mieux trier à Nantes'<br/><img src='resources/images/nantes/logo_mieuxtrieranantes.png' /><br/>'Mieux trier à Nantes' est une application android (gratuite) et un site http://mieuxtrieranantes.fr (qui présente le même contenu que l'application) pour les habitants de Nantes Métropole.<br/><br/>L'objectif est d'aider à trier.<br/>- savoir si un déchet est recyclable et les façons dont il peut être valorisé (avec des conseils spécifiques à chaque déchet),<br/>- connaître les emplacements des conteneurs, lieux et horaires des déchèteries et distribution des sacs jaunes et bleus,<br/>- connaître la filière tri à Nantes : centres de tri, associations nantaises, signification des logos...<br/>- connaître les organismes de la région qui se proposent de donner une seconde vie à vos déchets,<br/>- retrouver le mode de collecte et le jour de collecte à domicile (pour les Nantais recherche par rue, hors Nantes recherche par quartier).<br/><br/>C'est un logiciel libre qui s'appuie notamment sur les données Open Data de Nantes.<br/><br/>Nos coordonnées :<br/>- mail : mieuxtrieranantes@gmail.com<br/>- site Internet : <a href='http://mieuxtrieranantes.fr' target=_blank>http://mieuxtrieranantes.fr</a><br/>- blog : <a href='https://mieuxtrieranantes.wordpress.com' target=_blank>https://mieuxtrieranantes.wordpress.com</a><br/>- page Facebook : <a href='https://www.facebook.com/pages/Mieux-trier-%C3%A0-Nantes/266725983531595' taget=_blank>https://www.facebook.com/pages/Mieux-trier-%C3%A0-Nantes/266725983531595</a><br/>- page Google + : <a href='https://plus.google.com/115672613214762676111/posts' target=_blank>https://plus.google.com/115672613214762676111/posts</a><br/>- page Framasphere : <a href='https://framasphere.org/people/b0e79dd0547701326e712a0000053625' target=_blank>https://framasphere.org/people/b0e79dd0547701326e712a0000053625</a><br/>- utilisateur Tweeter : @MieuxTrierANant<br/>- les quiz : <a href='http://mieuxtrieranantes.e-monsite.com/quiz/' target=_blank>http://mieuxtrieranantes.e-monsite.com/quiz/</a>",
	"descr_en" : "Application and website of Better sort Nantes'<BR/><img src='resources/images/nantes/logo_mieuxtrieranantes.png' /><BR/>' better sort in Nantes is an android application (free) and http : //mieuxtrieranantes.fr (which has the same content as the application) to the people of Nantes Métropole<BR/>The goal is to help sort<BR/>- whether a. waste is recyclable and the ways it can be upgraded (with advice specific to each waste)<BR/>- the locations of containers, places and schedules of waste reception centers and distribution of yellow and blue bags,<BR/>- know the sort sector in Nantes: sorting centers, Nantes associations, meaning<BR/>logos ... - know the area organizations that offer to give a second life to your waste<BR/>- find it fashion and home collection collection day (for Nantais search by street outside Nantes search by area).<BR/>This is free software that relies particularly on Open Data Data . Nantes<BR/>Contact information:<BR/>- mail: mieuxtrieranantes@gmail.com<BR/>- website: <a href='http://mieuxtrieranantes.fr' target=_blank> http://mieuxtrieranantes.fr </a><BR/>- blog: <a href='https://mieuxtrieranantes.wordpress.com' target=_blank> https://mieuxtrieranantes.wordpress.com </a><BR/>- Facebook page: <a href='https://www.facebook.com/pages/Mieux-trier-%C3%A0-Nantes/266725983531595' taget=_blank> https: //www.facebook. com / pages / Wellness trier-% C3% A0-Nantes / 266725983531595 </a><BR/>- Google + page: <a href='https: //plus.google.com/115672613214762676111/posts' target='_blank'> https://plus.google.com/115672613214762676111/posts </a><BR/>- Framasphere page: <a href='https://framasphere.org/people/b0e79dd0547701326e712a0000053625' target=_blank> https: //framasphere.org/people/b0e79dd0547701326e712a0000053625 </a><BR/>- Tweeter User:MieuxTrierANant<BR/>- quiz: <a href='http: //mieuxtrieranantes.e-monsite.com/quiz/ 'target='_blank'> http://mieuxtrieranantes.e-monsite.com/quiz/ </a>",
	"bouton" : "fiche",
	"image" : "nantes/logo_mieuxtrieranantes.png",
	"mots_cles" : "mieux,trier,nantes",
	"mots_cles_en" : "mieux,trier,nantes"
}, {
	"code" : "fiche_plastik",
	"nom" : "PP Plastic Pickup",
	"nom_en" : "PP Plastic Pickup",
	"descr" : "Cette association est née d'une réflexion pour les membres fondateurs : je ramasse naturellement le plastique que je trouve. Deuxième constat : je ne suis pas isolé dans ce geste.<br/>Sous l’impulsion de la mairie de Rezé, l’association a été créée en 2012.<br/>L'objectif est de valoriser cet acte de ramassage, d'en faire un geste naturel et adopté par tous, de changer le regard sur ce déchet banalisé et dangereux pour l'environnement.<br/>Les 60 membres environ participent à des opérations nationales de <b>ramassage de déchets</b>comme les initiatives Océanes et le World Clean Up.<br/>RCette association ralise également des actions de sensibilisation du public comme le Plastic Flashmob et le Plastic Mobile.<br/>Voir la page <a href='www.plastiques.eu/' target=_new>www.plastiques.eu/</a>",
	"descr_en" : "Originally a reflection to the founding members, I naturally picks up the plastic I find. Second observation: I am not alone in this gesture. Under the leadership of the municipality of Rezé, the association was created in 2012.<BR/>The objective is to enhance this act of collecting, to make it a natural gesture and adopted by all, to change the look trivialized this waste and dangerous for the environment.<BR/>about 60 members involved in domestic operations like the Ocean initiatives and World Clean Up.<BR/>also Conducts public awareness actions like Plastic Flashmob Plastic and mobile.",
	"bouton" : "fiche",
	"image" : "nantes/logo_plasticpickup.png",
	"mots_cles" : "plastique,pp,plastic,pickup,oceane,reze",
	"mots_cles_en" : "pp,plastic,pickup,oceane,reze"
}, {
	"code" : "fiche_plus2vers",
	"nom" : "Plus2vers - échange de lombrics",
	"nom_en" : "Plus2vers - exchange of earthworms",
	"descr" : "Bourse aux lombrics et conseils sur le lombricompostage, essentiellement sur la région nantaise.<br/>(les lombrics sont utiliisés pour le lombricompostage)<br/><br/><img src='resources/images/nantes/logo_plus2vers.png' /><br/>Site internet qui permet de mettre en lien (gratuitement) des personnes qui veulent échanger des lombrics :<br/>Localiser sur une carte les donateurs de lombrics et contacter-les simplement en leur envoyant un mail.<br/>Vous trouverez ici des conseils très utiles pour réussir avec son lombricomposteur.<br/>300 donateurs sur la carte fin 2014.<br/><br/>Voir le site <a href='http://plus2vers.fr/' target=_blank >http://plus2vers.fr/</a>",
	"descr_en" : "Exchange earthworms and advice on vermicomposting, mainly in the Nantes region.<BR/>(Earthworms for vermicomposting are utiliisés)<BR/><img src='resources/images/nantes/logo_plus2vers.png' /><BR/>website that allows to link (free) for people who want to exchange earthworms.<BR/>Locate on a map earthworms donors and contact them by simply sending them an email < br /> Here you will find useful tips for success with his Vermicomposter<BR/>300 donors on the map<BR/>end of 2014. See the website <a href='http:. // plus2vers. fr / 'target='_blank'> http://plus2vers.fr/ </a>",
	"bouton" : "fiche",
	"image" : "nantes/logo_plus2vers.png",
	"mots_cles" : "plus2vers,echange,lombrics",
	"mots_cles_en" : "plus2vers,exchange,earthworms"
}, {
	"code" : "fiche_medicament",
	"nom" : "Récupération médicaments",
	"nom_en" : "Drugs recovery",
	"descr" : "<IMG SRC='resources/images/medicaments_petit.png' WIDTH='250px' /><br/>Il est impératif de ramener les médicaments en pharmacie. En effet ceux-ci finissent souvent dans les rivières ou les fleuves et les stations d'épuration ne peuvent pas tout éliminer.<br/><br/><b>Obligation de récolte...</b><br>Depuis juin 2009, <B>les pharmaciens ont obligation de collecter les Médicaments Non Utilisés (MNU)</B> (médicaments avec ou sans leurs conditionnements). <br><br/><b> ...pour incinération</b><br>L'association Cyclamed, qui réalisait soit une incinération soit un envoi vers les pays émergents, ne procède plus qu'à des incinérations depuis janvier 2009.<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>",
	"descr_en" : "<IMG src='resources/images/medicaments_petit.png' WIDTH='250px' /><BR/>It is imperative to bring the pharmacy drugs. Indeed they often end up in rivers or streams and wastewater treatment plants can not remove everything.<BR/><B> Obligation harvest ... </b> Since June 2009 <B> pharmacists are obliged to collect Drugs Not Used (MNU) </B> (drugs with or without their packaging). <br><BR/><b> ... for incineration </b> The Cyclamed association, which realized an incineration or sending to emerging countries, now only performs cremations since January 2009.<BR/><BR/><BR/><BR/>",
	"bouton" : "fiche",
	"image" : "medicaments_mini.png",
	"mots_cles" : "recuperation,medicaments",
	"mots_cles_en" : "recovery,medicine"
}, {
	"code" : "fiche_plusieurstrisac",
	"nom" : "Récupérer sacs jaunes et bleus",
	"nom_en" : "Collect yellow and blue bags",
	"descr" : "Il y a plusieurs moyens pour récupérer les rouleaux de sacs jaunes et bleus (trisacs) <li>- les 'rendez-vous' dans le quartier d'habitation (2 à 4 par an dans chaque quartier).<li>- les 'relais' : vous pouvez retirer 3 rouleaux de sacs (bleus et/ou jaunes). Vous pouvez vous y rendre 2 fois par an.<li>- les acheter : en supermarché ou dans des distributeurs automatiques (2,20 € le rouleau de 30 sacs).<br/><br/>Vente :<br/><img src='resources/images/vente_trisacs.jpg' width='250px' /><br>/<img src='resources/images/distributeur_trisac.jpg' width='250px' /><br/><br/>Les relais :<br/><img src='resources/images/relais_trisac.jpg'  width='250px' /><br/><br/><img src='resources/images/carte_retrait_trisacs.jpg' width='250px' />",
	"descr_en" : "There are several ways to retrieve the rolls of yellow and blue bags (trisacs) <li> - the 'appointment' in the residential area (2 to 4 per year in each district) <li> - the 'Relay' : You can remove 3 rolls of bags (blue and / or yellow). You can go there 2 times a year <li> - buy. In the supermarket or in vending machines (€ 2.20 the 30 bags roll)<BR/>Sale:<BR/>. <img src='resources/images/vente_trisacs.jpg' width='250px' /> <br/> <img src='resources/images/distributeur_trisac.jpg' width='250px' /><BR/><BR/>Relays:<BR/><img src='resources/images/relais_trisac.jpg' width='250px' /><BR/><img src='resources/images/carte_retrait_trisacs.jpg' width='250px' />",
	"bouton" : "fiche",
	"image" : "distributeur_trisac_mini.png",
	"mots_cles" : "recuperer,sacs,jaunes,bleus",
	"mots_cles_en" : "getbags,yellow,andblue"
}, {
	"code" : "fiche_acier",
	"nom" : "Recyclage acier",
	"nom_en" : "Steel recycling",
	"descr" : "<b>L'acier disparaît en 5-10 ans.</b><br/>Abandonnée à l'air libre, une boîte en acier mettrait de 5 à 10 ans à disparaître.<br/><br/><b>L'acier français provient à 47% du recyclage</B><br/>47 % de l'acier français correspond à la filière 'ferrailles' qui utilise exclusivement des ferrailles comme matières premières secondaires. Ces ferrailles sont notamment composées d'emballages ménagers triés par l'habitant.",
	"descr_en" : "<b> Steel disappears in 5-10 years. </b><BR/>abandoned in the open air, a steel box would put 5 to 10 years to disappear.<BR/><b>The French steel comes to 47% recycling </B><BR/>47% of the French steel industry is the 'scrap', which only uses scrap as secondary raw materials. The scrap is mainly comprised of household packaging sorted by the inhabitant.",
	"bouton" : "fiche",
	"image" : "aerosol_mini.png",
	"mots_cles" : "recyclage,acier",
	"mots_cles_en" : "recycling,steel"
}, {
	"code" : "fiche_recyclage_entreprse",
	"nom" : "Recyclage en entreprise",
	"nom_en" : "Recycling company",
	"descr" : "Nous détaillons ici uniquement les solutions nantaises dédiées aux entreprises : <B>ARBRES</B>L'association nantaise <b>A.R.B.R.E.S.</b> a 2 objectifs : récupérer certains déchets (surtout le papier et le carton, mais aussi cartouches d'encre et matériel electronique) et accompagner les bénéficiaires du RMI qui travaillent pour l'association. Elle dispose des récipients dans les entreprises, et s'occupe complètement . Plus d'infos sur <a href='http://arbres44.org'>http://arbres44.org</a>.<br/><img src='images/nantes/association_arbres.png' /><br/><br/><B>Solution Recyclage</B>Propose des solutions pour les entreprises : récupère plus de quarante déchets différents. Le papier, le carton, les bouteilles, la moquette, mais aussi les gobelets.<br/>Adresse : 181 Quai Emile Cormerais, 44800 Saint-Herblain<br/>Téléphone : 02 53 55 07 17<img src='images/nantes/logo_solutionrecyclage.png' /><br/><br/><B>Paprec</B>Paprec Group (parfois appelée Paprec Recyclage) est une société française de collecte et recyclage de déchets industriels et ménagers. Son site nantais est très actif. Ils récupèrent dans les entreprises tous les déchets, et gèrent la chaîne de bout en bout.",
	"descr_en" : "The association Nantes <b> TREES </b> has two objectives: to recover certain waste (Surtour paper and cardboard, but also ink cartridges and electronic equipment) and support RMI recipients who work for the association. It has containers in businesses, and handles completely. More information <a href='http://arbres44.org'> http://arbres44.org </a>.<BR/><img src='images/nantes/association_arbres.png' /><BR/>",
	"bouton" : "fiche",
	"image" : "nantes/association_arbres_mini.png",
	"mots_cles" : "recyclage,en,entreprise",
	"mots_cles_en" : "recyclingincompany"
}, {
	"code" : "fiche_pet",
	"nom" : "Recyclage plastique",
	"nom_en" : "Plastic recycling",
	"descr" : "Au centre de tri, les différents plastiques sont séparés en 3 catégories : PEHD (opaques) - PET clair - PET foncé.<BR/>Ils sont ensuite mis en balles pour être expédiés vers les usines de régénération.<BR/><BR/><UL><LI><B>Les bouteilles et flacons en PET (plastique généralement transparent)</B> sont majoritairement transformées en fibres (polyester) pour le rembourrage de couette, l'automobile, l'isolation de toiture plate.</LI><LI><B>Les emballages en PET</B> peuvent redonner des bouteilles ou d'autres emballages, à condition de respecter les législations ou pratiques en vigueur dans chaque pays pour le contact alimentaire.</LI><LI><B>Les bouteilles et flacons en PEHD (plastique généralement opaque)</B> deviennent des tubes, des bacs de coffrage pour les piscines, des conteneurs, du mobilier urbain ou des flacons de lessive.</LI></UL>",
	"descr_en" : "The sorting center, the various plastics are separated into 3 categories:. HDPE (opaque) - Clear PET - PET dark<BR/>They are then baled for shipment to the regeneration plants<BR/><BR/><UL> <LI> <B> The bottles and PET bottles (plastic generally transparent) </B> are mainly into fibers (polyester) for the quilt upholstery, automotive, insulation of flat roof . </LI><LI> <B> The PET packaging </B> may give bottles or other containers, provided you follow the laws or practice in force in each country for food contact. </LI><LI> <B> The bottles and HDPE bottles (plastic generally opaque) </B> become tubing, casing bins for pools, containers, street furniture or washing bottles. </LI></ UL>",
	"bouton" : "fiche",
	"image" : "bouteille_transparente_mini.png",
	"mots_cles" : "recyclage,plastique",
	"mots_cles_en" : "recyclingplastic"
}, {
	"code" : "fiche_tetrapak",
	"nom" : "Recyclage Tétrapak",
	"nom_en" : "Tetrapak recycling",
	"descr" : "<P class=informationsCss><IMG SRC='resources/images/brique_lait_mini.png' ALIGN='right' />Les Tétra Pak se composent de 3 matières : 75% environ de carton, 20% environ de polyéthylène, 5% environ d'aluminium. Ces composants se séparent très bien. <P class=informationsCss>En France 4 papetiers (2 situés en France, 1 en Espagne et 1 en Allemagne) récupèrent les emballages triés de Tetra Pak, puis séparent les matériaux dans des pulpeurs. <BR/><UL><LI>la partie carton est totalement recyclé,</LI><LI>le plastique-aluminium peut être transformé en une espèce de plastique, mais ça c'est très rarement le cas.</LI></LU><BR/><P class=informationsCss><B>C'est donc un produit recyclable (même si dans la réalité seul le carton l'est totalement), mais ce processus de récupération est assez polluant. Le verre l'est beaucoup moins.</B>",
	"descr_en" : "<P class=informationsCss> <IMG src='resources/images/brique_lait_mini.png' align='right' /> The Tetra Pak consist of three materials: cardboard about 75%, about 20% polyethylene, 5% aluminum. These components are separated very well. <P class=informationsCss> In France papermakers 4 (2 in France, 1 in Spain and 1 in Germany) recover the sorted packaging Tetra Pak, and then separate the materials into pulpers.<BR/><UL> <LI> the cardboard part is totally recycled, </LI><LI> plastic-aluminum can be transformed into a kind of plastic, but that's rarely the case. </LI></ LU><BR/><P class=informationsCss> <B> So it is a recyclable product (although in reality only the cardboard is completely), but this recovery process is quite polluting. The glass is much less. </B>",
	"bouton" : "fiche",
	"image" : "brique_lait_mini.png",
	"mots_cles" : "recyclage,tetrapak,brique",
	"mots_cles_en" : "recycling,tetrapak"
}, {
	"code" : "fiche_verre",
	"nom" : "Recyclage verre",
	"nom_en" : "Glass recycling",
	"descr" : "<B>On ne recycle que les bouteilles de verre et le verre d'emballage (bocaux...), qui se recycle à l'infini. Les autres types de verre et la vaisselle/porcelaine ne sont pas recyclables </B><BR/><I>Le verre culinaire et la vaisselle en verre ont une composition chimique différente du verre d'emballage qui rend impossible leur intégration au calcin utilisé dans les fours verriers. <BR/>Quant à la porcelaine, la faïence et la céramique, ce sont des matières infusibles qui rendent le calcin inutilisable. Elles forment des inclusions qui viennent fragiliser la bouteille.</I><BR/><BR/>Le verre collecté doit subir un premier tri manuel, puis plusieurs tris automatiques destinés à le débarrasser de ses impuretés. La collecte de verre de différentes couleurs est broyée en « calcin ». Ce calcin permet la fabrication de nouvelles bouteilles de couleur. S'il est 'surtrié' (tri par couleur dans un centre spécialisé), il pourra même donner des bouteilles incolores.",
	"descr_en" : "<B> One that recycles glass bottles and packaging glass (bottles ...), which can be recycled endlessly. Other types of glass and dishware / china are not recyclable </B><BR/><I> Culinary glass and glass tableware have a different chemical composition of glass packaging makes possible their integration into cullet used in glass furnaces.<BR/>As for porcelain, earthenware and ceramic, are infusible materials that make it unusable cullet. They form inclusions that come undermine the bottle. </ I><BR/><BR/>The collected glass must undergo a first manual sorting and several automatic sorting for the remove impurities. The collection of glass of different colors is ground into 'cullet'. This cullet permits the manufacture of new color bottles. If 'surtrié' (color sorting in a specialized center), it will even give colorless bottles.",
	"bouton" : "fiche",
	"image" : "bocal_verre_mini.png",
	"mots_cles" : "recyclage,verre",
	"mots_cles_en" : "recyclingglass"
}, {
	"code" : "fiche_velo",
	"nom" : "Réemploi vélo",
	"nom_en" : "Reuse bike",
	"descr" : "<IMG SRC='resources/images/veloenfant_petit.png'/>Il existe 4 associations spécialisées dans la récupération du vélo sur Nantes :<BR/><BR/> - <b>Place aux vélos</b> : les Brico-vélo sont des évènements organisés tous les premiers et troisièmes samedis de chaque mois, de 14h à 18h, au n°8 rue d'Auvours. Ces ateliers sont animés par des bénévoles et un salarié de Place au Vélo.<BR/><BR/> - <b>Vélocampus</b> est une association qui anime des ateliers participatifs et solidaires qui visent à fournir aux participants une certaine autonomie à l'entretien et la réparation de leur vélo. C'est ce qu'on appelle la vélonomie ! Ils permettent de nombreux échanges et une pratique pour acquérir, appliquer et aussi transmettre des savoir-faire dans ce domaine.Nous récupérons tous types de vélos, dans tous les états, pour leur offrir une seconde vie.<BR/><BR/>- <b>Transformeurs</b> (situé à Nantes, quartier Bellevue). Les vélos sont démontés et réparés avec les membres de l'association. Le jeudi de 17h à 20h, ainsi qu'un amedi sur deux (7 juin, 21 juin, 5 juillet et 19 juillet).<br/><br/> - <b>ATAO</b> (situé à Nantes et Saint-Herblain). ATAO est une association de réinsertion. Sur l'activité vélo, pour les entreprises et les particuliers : - vente de bicyclettes remises en état et garanties - location de bicyclettes afin de permettre d'organiser des sorties de groupe - L'entretien de bicyclettes de particuliers ou d'un parc d'entreprise.<BR/><BR/>Il existe des associations de réemploi qui récupérent les vélos en plus d'autres déchets : 'La Ressourcerie de l'ïle'...<br/><br/><b>Sources</b> : renseigné par les associations sur formulaire de mieuxtrieranantes.fr le 04/06/2014.",
	"descr_en" : "<IMG src='resources/images/veloenfant_petit.png' /> There are four associations specialized in bicycle recovery in Nantes:<BR/><BR/>- <b> Square bicycles </b>: Brico -vélo events are held every first and third Saturday of each month from 14h to 18h, at 8 rue Auvours. Workshops are led by volunteers and one employee of Place au Vélo<BR/><BR/>-. <B> Velocampus </b> is an association that conducts participatory workshops and solidarity that aim to provide participants with some autonomy for the maintenance and repair their bikes. It's called the vélonomie! They allow many exchanges and practical to acquire, apply and also transmit know-how in this domaine.Nous recover all bikes in all states, to offer them a second life.<BR/><BR/>- <b> Transformers </b> (located in Nantes, Bellevue neighborhood). The bikes are disassembled and repaired with members. Thursday from 17h to 20h, and a two amedi (7 June, 21 June and 19 July 5 July).<BR/>- <b> ATAO </b> (located in Nantes and Saint-Herblain). ATAO is a rehabilitation association. On the bike business, for companies and individuals: - sale of bicycles repaired and guarantees - bicycle rental to allow to organize group outings - Maintenance of specific bicycle or a park '.<BR/>business<BR/>exist reuse associations that collect bicycles in addition to other waste:' The Ressourcerie of the island ...<BR/><b> Sources </b>: sent by the associations on the form mieuxtrieranantes.fr 04/06/2014.",
	"bouton" : "fiche",
	"image" : "veloenfant_mini.png",
	"mots_cles" : "reemploi,velo,transformeurs,atao,place,autour",
	"mots_cles_en" : "reuse,bike,transformeurs,atao,place,autour"
}, {
	"code" : "fiche_reprise",
	"nom" : "Reprise magasins",
	"nom_en" : "Resumption stores",
	"descr" : "<img src='resources/images/recyclage_point_de_vente.jpg' width='250px' />Le décret 2005-829 du 20 juillet 2005 oblige la reprise des anciens appareils contre un nouveau. Ceci concerne les déchets 'D3E' (les équipements fonctionnant avec de l'électricité, sur secteur, par pile ou accumulateurs) : le gros et petit électroménager, le matériel audiovisuel, informatique...",
	"descr_en" : "<img src='resources/images/recyclage_point_de_vente.jpg' width='250px' /> Decree 2005-829 of 20 July 2005 requires the recovery of old against new devices. This concerns waste 'D3E' (equipment operating with electricity, mains, battery or accumulator): the large and small appliances, audiovisual equipment, computer ...",
	"bouton" : "fiche",
	"image" : "telephone_mini.png",
	"mots_cles" : "reprise,magasins",
	"mots_cles_en" : "recovery,stores"
}, {
	"code" : "fiche_sacjaune",
	"nom" : "Sacs jaunes et bleus",
	"nom_en" : "Yellow and blue bags",
	"descr" : "<IMG SRC='resources/images/nantes/sac_jaune_mini.png' ALIGN='right' WIDTH='150px' />L'opération Tri'sac correspond à des sacs jaunes et des sacs bleus.<br/><br/><UL>On peut mettre dans les sacs jaunes : <LI><B>le papier et le carton</B> : cartons (bruns), cartonnettes, emballage en carton, enveloppe, feuilles, journaux, magazines, prospectus,  boîte à œuf en carton, </LI> <LI><B>les briques alimentaires</B></LI> <LI><B>les flacons et bouteilles en plastiques (avec les bouchons)</B> : bouteille d'eau et de soda, bouteille d'huile (en plastique), tous les flacons</LI> <LI><B>les emballages en métal</B> : barquettes aluminium, canettes, boîtes de conserves, bombes aérosols</LI></UL><BR/><IMG SRC='resources/images/nantes/sac_bleu_mini.png' ALIGN='right' WIDTH='150px' /><br/> On met dans les sacs bleus les <B>déchets ménagers non recyclés</B>.",
	"descr_en" : "<IMG src='resources/images/nantes/sac_jaune_mini.png' align='right' WIDTH='150px' /> The Tri'sac operation corresponds to yellow bags and blue bags.<BR/><UL> You can put in yellow bags: <LI> <B> paper and cardboard </B>: cartons (brown), cardboards, carton, envelope, paper, newspapers, magazines, brochures, egg box cardboard </LI><LI> <B> Food brick </B> </LI><LI> <B> bottles and plastic bottles (with caps) </B>: water bottle and soda, oil bottle (plastic), all bottles </LI><LI> <B> metal packaging </B>: aluminum trays, cans, tins, aerosols </LI></UL><BR/><IMG src='resources/images/nantes/sac_bleu_mini.png' align='right' WIDTH='150px' /><BR/>are placed in blue bags the <B> household wastes not recycled </B>.",
	"bouton" : "fiche",
	"image" : "nantes/sacs_jaune_et_bleu.png",
	"mots_cles" : "sacs,jaunes,bleus",
	"mots_cles_en" : "bags,yellow,blue"
},

{
	"code" : "fiche_telephone",
	"nom" : "Numéros de téléphones",
	"nom_en" : "Phone numbers",
	"descr" : "AlloNantes est un numéro gratuit pour les Nantais (notamment pour les questions sur le tri). Ouvert de 8h à 19h du lundi au vendredi, et le samedi de 8h à 13h.<br/><br/>Pour les autres villes, joindre les pôles de proximité:<br/>Pôle Erdre et Loire<br/>Sainte-Luce-sur-Loire, Nantes : quartiers Bottière-Doulon-Erdre,Mauves-sur-Loire, Carquefou<br/>2-4, rue Edouard Nignon<br/>44300 Nantes<br/>Tél : 02 28 20 22 00<br/><br/>Pôle Erdre-et-Cens<br/>Orvault,La-Chapelle-sur-Erdre,Sautron,Nantes quartiers Nord<br/>37, bd Einstein<br/>44300 Nantes<br/>Tél : 02 51 83 65 00<br/><br/>Pôle Loire, Sèvre et Vignoble<br/>Rezé, Saint-Sébastien-sur-Loire,Nantes: quartier sud, Basse-Goulaine, Les-Sorinières, Vertou<br/>6 rue Marie Curie<br/>44120 Vertou<br/>Tél : 02 72 01 26 00<br/><br/>Pôle Loire-Chézine<br/>Couëron, Indre, Saint-Herblain<br/>6, rue Virginia Woolf<br/>44800 Saint-Herblain<br/>Tél : 02 28 03 41 50<br/><br/>Pôle Nantes-Loire<br/>Centre ville, Malakoff, Saint-Donatien, Île-de-Nantes<br/>14 Mail Pablo Picasso<br/>44000 Nantes<br/>Tél : 02 51 86 54 00<br/><br/>Pôle Nantes-Ouest<br/>Bellevue, Chantenay, Sainte-Anne Dervallières, Zola, Hauts-Pavés, Saint-Félix, Breil,Barberie<br/>La Maison des services publics<br/>Place de la Liberté<br/>44100 Nantes<br/>Tél : 02 28 03 47 00<br/><br/>Pôle Sud-Ouest<br/>Bouaye, Bouguenais, Brains, Le-Pellerin, La-Montagne, Saint-Jean-de-Boisseau, Saint-Aignan-de-Grand-Lieu, Saint-Léger-les-Vignes<br/>2, rue Galilée<br/>44340 Bouguenais<br/>Tél. : 02 28 00 16 00<br/>",
	"descr_en" : "AlloNantes is a free number for Nantais (including questions about sorting). Open from 8 am to 19h from Monday to Friday, and Saturday from 8 to 13h<BR/>For other cities, joining the poles of proximity.<BR/>Pole Erdre et Loire Sainte<BR/>-Luce-sur-Loire, Nantes-Erdre Bottière-Doulon neighborhoods Mauves-sur-Loire, Carquefou<BR/>2-4, rue Edouard Nignon<BR/><BR/>44300 Nantes Tel: 28 February 20 22<BR/>Erdre 00 Pole-and-Cens<BR/>Orvault, La-Chapelle-sur-Erdre, Sautron Nantes Nord neighborhoods<BR/>37, bd<BR/>Einstein 44300 Nantes<BR/>Tel: 02 51 83 65 00<BR/>Pole Loire, Sevre and Vineyard<BR/>Rezé, Saint-Sébastien-sur-Loire, Nantes southern district, Lower Goulaine, Les-Sorinieres, Vertou<BR/>6 rue Marie Curie 44120 Vertou<BR/><BR/>Tel: 26 January 00 February 72<BR/>Pole Chézine<BR/>Couëron Loire, Indre, Saint-Herblain < br /> 6, rue Virginia Woolf<BR/>44800 Saint-Herblain<BR/>Tel: 02 28 March 41 50<BR/>Pole Nantes-Loire<BR/>Downtown, Malakoff, Saint Donatien, Ile de Nantes 14<BR/>Mail Pablo Picasso<BR/><BR/>44000 Nantes Tel: 02 51 86 54 00<BR/>Nantes West Pole<BR/>Bellevue, Chantenay, St. Anne Dervallières, Zola, Hauts-Pavers, St. Felix, Breil, Barberie<BR/>House utilities<BR/>Freedom Square<BR/><BR/>44100 Nantes Tel: 02 March 28 47 00<BR/>Pole Southwest<BR/>Bouaye Bouguenais, Brains, Le-Pellerin, La Montagne, Saint-Jean-de-Boisseau, Saint-Aignan-de-Grand Place Saint-Léger-les-Vignes<BR/>2, Rue Galilee 44340 Bouguenais<BR/><BR/>Tel. : 02 28 00 16 00<BR/>",
	"bouton" : "fiche",
	"image" : "phone_black.png",
	"mots_cles" : "allo,allonantes,proximite,telephone,tel,appeler,doute,question",
	"mots_cles_en" : "allo,allonantes,proximity,telephone,phone,call,doubt,question"
}, {
	"code" : "fiche_arcenciel",
	"nom" : "Usine Arc-en-ciel",
	"nom_en" : "Arc-en-ciel Factory",
	"descr" : "<IMG SRC='resources/images/nantes/usine_arcenciel.jpg' ALIGN='left' />Ce dispositif a été mis en service en mars 1994 et il comprend 4 unités : <UL><LI>le centre de traitement et de valorisation des déchets,</LI><LI>le centre de tri et de conditionnement des déchets ménagers recyclables,</LI><LI> le centre de tri des déchets industriels et commerciaux, situé à Couëron,</LI><LI> l'unité de compostage de déchets verts située à Saint-Herblain.,</LI></UL><BR/>Vous pouvez visiter l'usine.",
	"descr_en" : "<IMG src='resources/images/nantes/usine_arcenciel.jpg' align='left' /> The scheme was commissioned in March 1994 and includes 4 units: <UL> <LI> the center of treatment and recovery of waste </LI><LI> the sorting center and conditioning of recyclable household waste </LI><LI> the sorting center of industrial and commercial waste, located in Couëron, </LI><LI> l green waste composting plant located in Saint-Herblain. </LI></UL><BR/>You can visit the factory.",
	"bouton" : "fiche",
	"image" : "nantes/usine_arcenciel_mini.png",
	"mots_cles" : "usine,arc,ciel,arc,ciel,coueron",
	"mots_cles_en" : "factory,arc,ciel,coueron"
}, {
	"code" : "fiche_valorena",
	"nom" : "Usine Valorena",
	"nom_en" : "Valorena factory ",
	"descr" : "<IMG SRC='resources/images/nantes/usine_valorena.jpg' ALIGN='left' /><br/>Cette usine d'incinération d'ordures ménagères  a été mise en service en octobre 1987, elle alimente un réseau de chauffage urbain grâce à l'énergie récupérée lors de la combustion des déchets.<BR/><BR/>Elle est situé à proximité de la route Nantes, Angers (au bord de la voie SNCF)<BR/><BR/>Consultez le site Internet : <A HREF='http://www.novergie.fr/page/groupe/usines/usine.php?id=34' TARGET='NEW' >valorena</A><br/><A HREF='http://www.youtube.com/watch?v=H69lhVN7QXE' target='_blank'>Vidéo de présentation (3 minutes)</A><br/>Des visites de l'usine sont proposées toutes l'année.",
	"descr_en" : "<IMG src='resources/images/nantes/usine_valorena.jpg' align='left' /><BR/>This incinerator household waste was commissioned in October 1987, it feeds a heating network Urban thanks to the energy recovered during waste combustion.<BR/><BR/>It is located near the road Nantes, Angers (along the train route)<BR/><BR/>Check Website: <A HREF='http://www.novergie.fr/page/groupe/usines/usine.php?id=34' TARGET='NEW'> valorena </A><BR/><A HREF='http://www.youtube.com/watch?v=H69lhVN7QXE' target='_blank'> Overview Video (3 minutes) </A><BR/>Tours of the factory are offered all the year.",
	"bouton" : "fiche",
	"image" : "nantes/usine_valorena.png",
	"mots_cles" : "usine,valorena",
	"mots_cles_en" : "factory,valorena"
}, {}];
