var _quizsDatas = {
	'quiz1' : {
		nom : "Quiz spécial janvier (5 questions)",
		descr : "Tester vos connaissances sur le tri sur Nantes Métropole. Une seule réponse par question.",
		image : "resources/images/quiz/issiontrix-quiz-1.jpg",
		src : "MieuxTrierANantes 01/2015",
		nbq : "5",
		ok : "q1r1,q2r1,q3r1,q4r1,q5r1",
		q1 : "Que faire de la couronne que j'ai gagné ? Elle est propre.",
		q1r1 : "je la laisse sur ma tête",
		q1r2 : "le carton/papier ne se recycle pas",
		q1r3 : "je la recycle (bac jaune ou sac jaune)",
		q1i1 : "resources/images/quiz/couronne.png",
		q1e1 : "Tout le carton/papier se recycle, sauf s'il est souillé (sali)",
		// q1ok : "q1r1",
		q2 : "La fève de la galette...",
		q2r1 : "j'avale",
		q2r2 : "je jette ! (sac bleu ou bac bleu)",
		q2r3 : "je recycle !",
		q2i1 : "resources/images/quiz/issiontrix-feve-1.png",
		q2e1 : "Les fèves sont en porcelaine. Donc elle se jette (c'est uniquement le verre ménager qui se recycle).",
		// q2ok : "a",
		q3 : "Le logo 'point vert' de Eco-emballage signifie...",
		q3r1 : "que l'emballage est recyclable",
		q3r2 : "que l'emballage est fabriqué à partir de matières recyclables",
		q3r3 : "que le fabriquant verse une contribution à Eco-Emballage, Adelphe ou Cyclamed",
		q3i1 : "resources/images/quiz/point-vert.png",
		q3e1 : "L'ancien logo 'point vert' signifie que le fabriquant verse une contribution à l'une de ces trois sociétés : Eco-Emballage, Adelphe ou Cyclamed; ceci ne signifie pas que le produit est recyclable.",
		// q3ok : "a",
		q4 : "Le nouveau logo Triman apparu en janvier 2015.",
		q4r1 : "signifie qu'il existe des consignes de tri",
		q4r2 : "que le fabricant paye pour avoir ce logo",
		q4r3 : "que l'emballage est fabriqué à partir de matières recyclables",
		q4i1 : "resources/images/quiz/triman.png",
		q4e1 : "Le nouveau logo 'Triman' représente une personne tendant la main vers trois flèches. Il signifie qu'il existe des consignes de tri",
		// q4ok : "a",
		q5 : "Que faire du bouchon en liège ?",
		q5r1 : "Je le recycle (bac jaune ou sac jaune)",
		q5r2 : "Je jette (bac bleu ou sac bleu) ou je le donne à l'asso Les Bouchons d'Amour",
		q5r3 : "Je jette (bac bleu ou sac bleu) ou je le donne à l'association Action Cancer 44",
		q5i1 : "resources/images/quiz/bouchon-1.png",
		q5e1 : "Pour les bouchons en liège (qui ne se recyclent pas) c'est l'association 'Action Cancer 44' qui les récupèrent."
	},
	'quiz2' : {
		nom : "Quiz Hellfest",
		descr : "Quiz spécial métal et bière pour Hellfest",
		image : "resources/images/quiz/issiontrix_hellfest.png.jpg",
		src : "MieuxTrierANantes 05/2015",
		nbq : "5",
		q1 : "La canette en métal",
		q1r1 : "se boit et se recycle (c'est un objet 'gros' en aluminium)",
		q1r2 : "se boit et ne se recycle pas.",
		q1r3 : "c'est mauvais pour moi, je n'en prends pas.",
		q1i1 : "resources/images/quiz/",
		q1e1 : "Elle est fabriquée en aluminium. Les objets en aluminium se recyclent (sauf les petits objets). Il faut par exemple 670 canettes pour fabriquer un vélo",
		q1ok : "q1r1",
		q2 : "La canette en verre",
		q2r1 : "se boit et se recycle",
		q2r2 : "se boit et ne se recycle pas.",
		q2r3 : "je la garde pour mettre un bateau dedans",
		q2i1 : "resources/images/quiz/",
		q2e1 : "Tout le verre 'ménager' se recycle : les bouteilles, les bocaux. Mais les verres à boire ne se recyclent pas.",
		q2ok : "q2r1",
		q3 : "Le gobelet en plastique jetable",
		q3r1 : "je le conserve pour la prochaine fois",
		q3r2 : "il se recycle",
		q3r3 : "il se met à la poubelle",
		q3i1 : "resources/images/quiz/tirebouchon.png",
		q3e1 : "Comme ce n'est ni un flacon ni une bouteille il ne se recycle pas.",
		q3ok : "q3r3",
		q4 : "Le gobelet en plastique réutilisable",
		q4r1 : "je n'aime pas ça.",
		q4r2 : "je te rends contre la caution ou je la conserve pour un prochain concert",
		q4r3 : "je le recycle",
		q4i1 : "resources/images/quiz/",
		q4e1 : "Evidemmment ils doivent reservir. Comme ce n'est ni un flacon ni une bouteille il ne se recycle pas.",
		q4ok : "q4r2",
		q5 : "La capsule sur la bouteille de bière",
		q5r1 : "s'avale",
		q5r2 : "se recycle",
		q5r3 : "se met dans la poubelle",
		q5i1 : "resources/images/quiz/",
		q5e1 : "Elles sont fabriquées en acier (qui est un matériau recyclable) mais leur petite quantité de métal les rend peut intéressant économiquement pour le recyclage. Il faut les mettre dans la poubelle ou le sac bleu.",
		q5ok : "q5r3"
	},
	'quizx' : {
		nom : "",
		descr : "",
		image : "resources/images/quiz/",
		src : "MieuxTrierANantes 05/2015",
		nbq : "5",
		q1 : "",
		q1r1 : "",
		q1r2 : "",
		q1r3 : "",
		q1i1 : "resources/images/quiz/",
		q1e1 : "",
		q1ok : "",
		q2 : "",
		q2r1 : "",
		q2r2 : "",
		q2r3 : "",
		q2i1 : "resources/images/quiz/",
		q2e1 : "",
		q2ok : "",
		q3 : "",
		q3r1 : "",
		q3r2 : "",
		q3r3 : "",
		q3i1 : "resources/images/quiz/",
		q3e1 : "",
		q3ok : "",
		q4 : "",
		q4r1 : "",
		q4r2 : "",
		q4r3 : "",
		q4i1 : "resources/images/quiz/",
		q4e1 : "",
		q4ok : "",
		q5 : "",
		q5r1 : "",
		q5r2 : "",
		q5r3 : "",
		q5i1 : "resources/images/quiz/",
		q5e1 : "",
		q5ok : ""
	}
};