var _specificLabelsDatas = {
	'a_propos' : {
		"fr" : "Pour aider les habitants de Nantes Métropôle à trier",
		"en" : "« Mieux trier à Nantes », v. 1.16"
	},
	'about_titre' : {
		"fr" : "« Mieux trier à Nantes », v. 1.16",
		"en" : "Tto help inhabitants of Nantes Métropole to sort."
	},
	'about' : {
		"fr" : "Application android (gratuite) et site mieuxtrieranantes.fr pour aider les habitants de Nantes Métropole à trier. C'est un logiciel libre (code, photos, données) réalisé par l'association 'Mieux trier à Nantes' (dont Christian Renoulin et Romain Debernardi).<br/><br/><a href='https://mieuxtrieranantes.wordpress.com'>blog</a>  <A HREF='https://www.facebook.com/pages/Mieux-trier-à-Nantes/266725983531595' TARGET=_blank title='Facebook'><IMG SRC='resources/icons/facebook.png' HEIGHT='18px' style='vertical-align:middle;'/></A>  <A HREF='https://plus.google.com/115672613214762676111/posts' ><IMG SRC='resources/icons/googleplus.png' HEIGHT='18px' style='vertical-align:middle;'/></A>  <A HREF='https://framasphere.org/people/b0e79dd0547701326e712a0000053625' ><IMG SRC='resources/icons/framasphere.png' HEIGHT='18px' style='vertical-align:middle;'/></A> <IMG SRC='resources/icons/twitter.png' HEIGHT='18px' style='vertical-align:middle;'/><font size='1'>@MieuxTrierANant</font><br/>Contacts : <i><a href='mailto:mieuxtrieranantes@gmail.com'><font size='2'>mieuxtrieranantes@gmail.com</font></a></i><br/><br/>Amis : <IMG SRC='resources/images/images_non_libres/logo_les_boites_vertes_rogne_mini.png' HEIGHT='22px' style='vertical-align:middle;'/>&nbsp;&nbsp;<A HREF='http://lesboitesvertes.fr/' TARGET=_blank title='Association les boîtes vertes (Baludik, PlusDeVers)'>les boîtes vertes</A>",
		"en" : "Android application (free) and mieuxtrieranantes.fr website to help inhabitants of Nantes Métropole to sort. It is open source software (code, images, data) created by the association (including Christian Renoulin and Romain Debernardi).<br/><br/><a href='https://mieuxtrieranantes.wordpress.com'>blog</a>  <A HREF='https://www.facebook.com/pages/Mieux-trier-à-Nantes/266725983531595' TARGET=_blank title='Facebook'><IMG SRC='resources/icons/facebook.png' HEIGHT='18px' style='vertical-align:middle;'/></A>  <A HREF='https://plus.google.com/115672613214762676111/posts' ><IMG SRC='resources/icons/googleplus.png' HEIGHT='18px' style='vertical-align:middle;'/></A>  <A HREF='https://framasphere.org/people/b0e79dd0547701326e712a0000053625' ><IMG SRC='resources/icons/framasphere.png' HEIGHT='18px' style='vertical-align:middle;'/></A> <IMG SRC='resources/icons/twitter.png' HEIGHT='18px' style='vertical-align:middle;'/><font size='1'>@MieuxTrierANant</font><br/>Contacts : <i><a href='mailto:mieuxtrieranantes@gmail.com'><font size='2'>mieuxtrieranantes@gmail.com</font></a></i><br/><br/>Friends : <IMG SRC='resources/images/images_non_libres/logo_les_boites_vertes_rogne_mini.png' HEIGHT='22px' style='vertical-align:middle;'/>&nbsp;&nbsp;<A HREF='http://lesboitesvertes.fr/' TARGET=_blank title='Association les boîtes vertes (Baludik, PlusDeVers)'>les boîtes vertes</A>"
	},
	'zz' : {}
};
