var _usualCategoriesDatas = [
{"code":"cu_plastique","libelle":"Plastique Brique","sousCategories":"false","image":"grande_bouteille_huile_mini.png","bouton":"cu"},
{"code":"cu_papierscartons","libelle":"Papier Carton","sousCategories":"false","image":"cartonette_mini.png","bouton":"cu"},
{"code":"cu_metal","libelle":"Métal","sousCategories":"false","image":"barquette_aluminium_mini.png","bouton":"cu"},
{"code":"cu_vertbois","libelle":"Déchet vert Bois","sousCategories":"false","image":"feuillages_mini.png","bouton":"cu"},
{"code":"cu_verrevaisselle","libelle":"Verre Vaisselle","sousCategories":"false","image":"vase_mini.png","bouton":"cu"},
{"code":"cu_vetementtissu","libelle":"Vêtement Tissu","sousCategories":"false","image":"jean_usage_mini.png","bouton":"cu"},
{"code":"cu_encombrantelectronique","libelle":"Encombrant Électronique","sousCategories":"false","image":"refrigerateur_mini.png","bouton":"cu"},
{"code":"cu_divers","libelle":"Divers","sousCategories":"false","image":"bouchon_liege_mini.png","bouton":"cu"},
{"code":"scu_medicament","libelle":"Médicament","sousCategories":"true","image":"medicaments_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquejardin","libelle":"Déchet toxique du Jardinage","description_fr":" Engrais chimiques, herbicides, fongicides, insecticides...","sousCategories":"true","image":"desherbant_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquegarage","libelle":"Déchet toxique du Garage","description_fr":" Antigel, liquide de refroidissement, mastic de carrosserie, peinture antirouille, huile minérale, filtre à huile...","sousCategories":"true","image":"batterie_voiture_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquecuisine","libelle":"Déchet toxique de la Cuisine","description_fr":"Nettoyants cuivre et argenterie, nettoyants à l’ammoniac, récurant pour four...","sousCategories":"true","image":"bouteille_ammoniaque_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquesdb","libelle":"Déchet toxique de la Salle de bain","description_fr":"Déboucheur liquide, détachant, eau de Javel, nettoyants à sol, récurant pour toilette, thermomètres à mercure...","sousCategories":"true","image":"desinfectant_toilette_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquebrico","libelle":"Déchet toxique du Bricolage","description_fr":"Colles, produits de traitement du bois, enduits et vernis, peintures huile et eau,  laques, résines, diluants, solvants...","sousCategories":"true","image":"peinture_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiqueparasite","libelle":"Déchet toxique du traitement des parasites","description_fr":"Anti-fourmis, insecticides, naphtaline, mort aux rats...","sousCategories":"true","image":"mortaurat_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquedivers","libelle":"Déchet toxique divers","description_fr":"acides, bases, essence de térébenthine, radiographie, révélateur et fixateur photo, néons...","sousCategories":"true","image":"pile_45_mini.png","bouton":"cu_toxique"},
{"code":"cu_toxique","libelle":"Toxique","estSousCategorie":"scu_medicament,scu_toxiquejardin,scu_toxiquegarage,scu_toxiquecuisine,scu_toxiquesdb,scu_toxiquebrico,scu_toxiqueparasite,scu_toxiquedivers","sousCategories":"false","image":"batterie_voiture_mini.png","bouton":"cu"},
{}];
