var _usualCategoriesDatas = [
{"code":"cu_plastique","nom":"Plastique Brique","sous_cat":"false","image":"bouteille_lait_mini.png","bouton":"cu"},
{"code":"cu_papierscartons","nom":"Papier Carton","sous_cat":"false","image":"journal_mini.png","bouton":"cu"},
{"code":"cu_metal","nom":"Métal","sous_cat":"false","image":"bidon_metal_mini.png","bouton":"cu"},
{"code":"cu_vertbois","nom":"Déchet vert Bois","sous_cat":"false","image":"epeluchure_mini.png","bouton":"cu"},
{"code":"cu_verrevaisselle","nom":"Verre Vaisselle","sous_cat":"false","image":"vase_mini.png","bouton":"cu"},
{"code":"cu_vetementtissu","nom":"Vêtement Tissu","sous_cat":"false","image":"jean_usage_mini.png","bouton":"cu"},
{"code":"cu_encombrantelectronique","nom":"Encombrant Élec.","sous_cat":"false","image":"refrigerateur_mini.png","bouton":"cu"},
{"code":"cu_divers","nom":"Divers","sous_cat":"false","image":"rouge_a_levre_mini.png","bouton":"cu"},
{"code":"scu_medicament","nom":"Médicament","sous_cat":"true","image":"medicaments_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquejardin","nom":"Déchet toxique du Jardinage","descr":" Engrais chimiques, herbicides, fongicides, insecticides...","sous_cat":"true","image":"desherbant_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquegarage","nom":"Déchet toxique du Garage","descr":" Antigel, liquide de refroidissement, mastic de carrosserie, peinture antirouille, huile minérale, filtre à huile...","sous_cat":"true","image":"batterie_voiture_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquecuisine","nom":"Déchet toxique de la Cuisine","descr":"Nettoyants cuivre et argenterie, nettoyants à l’ammoniac, récurant pour four...","sous_cat":"true","image":"bouteille_ammoniaque_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquesdb","nom":"Déchet toxique de la Salle de bain","descr":"Déboucheur liquide, détachant, eau de Javel, nettoyants à sol, récurant pour toilette, thermomètres à mercure...","sous_cat":"true","image":"desinfectant_toilette_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquebrico","nom":"Déchet toxique du Bricolage","descr":"Colles, produits de traitement du bois, enduits et vernis, peintures huile et eau,  laques, résines, diluants, solvants...","sous_cat":"true","image":"peinture_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiqueparasite","nom":"Déchet toxique du traitement des parasites","descr":"Anti-fourmis, insecticides, naphtaline, mort aux rats...","sous_cat":"true","image":"mortaurat_mini.png","bouton":"cu_toxique"},
{"code":"scu_toxiquedivers","nom":"Déchet toxique divers","descr":"acides, bases, essence de térébenthine, radiographie, révélateur et fixateur photo, néons...","sous_cat":"true","image":"pile_45_mini.png","bouton":"cu_toxique"},
{"code":"cu_toxique","nom":"Toxique","estSousCategorie":"scu_medicament,scu_toxiquejardin,scu_toxiquegarage,scu_toxiquecuisine,scu_toxiquesdb,scu_toxiquebrico,scu_toxiqueparasite,scu_toxiquedivers","sous_cat":"false","image":"batterie_voiture_mini.png","bouton":"cu"},
{}];
